### ISSUE TITLE
menu positioning/activation for Windows pinned shortcuts?

### ISSUE THREAD

**Issue by trefrog** [andryou/scriptsafe#10]
well here's a low-priority annoyance...

(on facebook.com, in this instance...) I go to Menu > More Tools > Add To Desktop ('open as window' checked), and pin this to the taskbar. Then via chrome://extensions, set a keyboard shortcut [Alt-Z] to activate ScriptSafe. A few versions back, I used to be able to use this, and the menu would appear at the top left of the window. Now it seems to either be obscured or not firing at all. Chrome also had a few updates recently, so maybe it's something on their end.

// as an aside... Chrome on XP never could activate by shortcut properly (in a "pinned app" window) anyway,  1/4 of the menu would show on the inside top-left edge of the window, but the rest was cut off by the window frame. and yes, I do still use XP at work. It's very painful, in general.

**Comment by andryou** [comment]
Thanks for the description; which versions of ScriptSafe, Chrome, and Windows are you using? (I'm assuming Windows XP?)

I tried reproducing this (ScriptSafe v1.0.7.1, Chrome 50.0.2661.94 m, and Windows 7 64-bit), and Alt-Z toggled the ScriptSafe panel.

Does this issue occur with other extensions as well?

**Comment by trefrog** [comment]
ScriptSafe v1.0.7.0
Version 51.0.2704.63 m (64-bit)
Windows 10 Pro [10.0.10586]

no, the XP machine is at work, and I really don't care about most of its problems, if I can help it. To be clear, I'm talking about the "minimal" Chrome window, no toolbar/omnibar/etc, hence the need for a shortcut.

I tried the Google Calendar extension, which uses a similar flyout menu. Then I tried "Tabs Outliner", which launches a separate window where all the action is. I also tried setting a different hotkey, [Ctrl+Shift+F]... nothing, in all cases. Maybe it's a Chrome vs. Windows 10 thing?

**Comment by andryou** [comment]
Sorry for the delay in getting back to you on this issue. 

To my knowledge, the "Activate extension" hotkey item *should* trigger the flyout menu and no action is required on the part of extension developers to build in listeners/handlers for this.

I wish this was something I could fix for you but unfortunately it does sound like it's beyond the scope of this extension (or any other) and sounds like a potential Chrome vs. Windows 10 issue.
