### ISSUE TITLE
Add a remark to "Prevent Clipboard Interference"

### ISSUE THREAD

**Issue by tjuerges** [andryou/scriptsafe#100]
This is not an issue as in bug but it is about adding a remark to the explanation of the "Prevent Clipboard Interference" setting.

When "Prevent Clipboard Interference" is enabled, Google's Web Mail client will not switch between the Gmail/Contacts/Tasks views when the corresponding menu entry is selected. A remark about this in the explanation of the setting would be appreciated.

**Comment by andryou** [comment]
v1.0.8.5 has officially been released which now gives you the ability to allow certain Fingerprint Protection options on a per-domain basis :)

**Comment by tjuerges** [comment]
Sorry for not getting back to you earlier.  This works as expected.  Thank you very much!
