### ISSUE TITLE
WEBUGS: Can't enable/disable them and some websites don't work because they are just blocked

### ISSUE THREAD

**Issue by Enigma0** [andryou/scriptsafe#102]
WEBUGS: Can't enable/disable them and some websites don't work because they are just blocked.

I've run across the occasional site that despite allowing pretty much everything (facebook excluded) I still can't get some element to load properly.

<strike>One example is: https://www.humblebundle.com/store where I just have a constant loading animation.</strike>

Edit: this example no longer applies.

**Comment by AykutCevik** [comment]
Seems also to be the same as #127

**Comment by andryou** [comment]
I've released a beta version of v1.0.8.5 which incorporates a fix for this issue: #140. Feel free to test and confirm.

**Comment by andryou** [comment]
v1.0.8.5 which contains a fix for this has officially been released.
