### ISSUE TITLE
scriptsafe

### ISSUE THREAD

**Issue by totrungmobile** [andryou/scriptsafe#103]
annoyances|true
annoyancesmode|relaxed
antisocial|false
applet|true
audio|true
audioblock|false
battery|false
blackList|[]
canvas|false
canvasfont|false
classicoptions|false
clientrects|false
clipboard|false
cookies|true
domainsort|true
embed|true
enable|true
frame|true
gamepad|false
hashchecking|false
iframe|true
image|true
keyboard|false
lastSync|1472883475309
linktarget|off
mode|block
noscript|true
object|true
optionslist|true
paranoia|false
preservesamedomain|false
rating|true
referrer|true
referrerspoof|off
refresh|true
script|true
sync|true
syncenable|true
syncfromnotify|true
syncnotify|true
tempregexflag|true
timezone|false
uaspoofallow|false
updatenotify|true
useragentspoof|off
useragentspoof_os|off
utm|false
video|true
webbugs|true
webgl|false
webrtc|default_public_interface_only
webrtcdevice|false
whiteList|["_.googlevideo.com","_*.github.com","lg.com","ajax.googleapis.com"]
xml|true

**Comment by andryou** [comment]
I'm not too sure if this is an issue, please create another issue with more detail if needed. Thanks!
