### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by triceratops1** [andryou/scriptsafe#104]
do you plan give support to firefox

**Comment by MattMS** [comment]
There is [NoScript](https://addons.mozilla.org/en-US/firefox/addon/noscript/) for Firefox.

**Comment by andryou** [comment]
Along with what @MattMS mentioned, NoScript is an excellent, feature-rich extension. I currently don't have any plans to develop a Firefox build of ScriptSafe.

**Comment by andryou** [comment]
Wish granted: https://addons.mozilla.org/en-US/firefox/addon/script-safe/
