### ISSUE TITLE
Disqus login problems

### ISSUE THREAD

**Issue by jawz101** [andryou/scriptsafe#107]
I cannot, for the life of me, get Disqus to log in properly and stick.

http://www.androidpolice.com/2016/09/06/turing-monolith-chaconne-because-cadenza-was-too-weak/

Current settings (excluding my whitelist and sync setting entries since they're irrelevant)

annoyances|true
annoyancesmode|relaxed
antisocial|false
applet|true
audio|true
audioblock|true
battery|true
blackList|[]
canvas|blank
canvasfont|true
classicoptions|false
clientrects|false
clipboard|true
cookies|true
domainsort|true
embed|true
enable|true
frame|true
gamepad|true
hashchecking|true
iframe|true
image|false
keyboard|false
linktarget|off
mode|block
noscript|false
object|true
optionslist|false
paranoia|false
preservesamedomain|true
rating|false
referrer|true
referrerspoof|off
refresh|true
script|true
tempregexflag|true
timezone|random
uaspoofallow|false
updatenotify|true
useragentspoof|off
useragentspoof_os|off
utm|true
video|true
webbugs|true
webgl|true
webrtc|default_public_interface_only
webrtcdevice|true
whiteList|[]
xml|all

**Comment by andryou** [comment]
v1.0.8.5 has officially been released. Could you please retest (once you verify that ScriptSafe v1.0.8.5 is installed) and let me know if the issue is still present? Thanks!
