### ISSUE TITLE
Extension error with ScriptSafe and µBlock Origin

### ISSUE THREAD

**Issue by Diftraku** [andryou/scriptsafe#11]
With certain files (I suspect with tracking pixels), µBlock Origin tries to redirect it to some other file, but ScriptSafe hijacks the redirect, causing an extension error on Google Chrome.

> Warning:
>> This extension failed to redirect a network request to data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw== because another extension (ScriptSafe) redirected it to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACklEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg==.

Both extension continue function as expected, thus making this more of an annoyance.

OS: Windows 10 Pro
Google Chrome: 51.0.2704.63
ScriptSafe: 1.0.7.1
µBlock Origin: 1.7.2

**Comment by andryou** [comment]
Unfortunately I won't be able to fix this (e.g. I can't list what other Chrome extensions are listed, and even if I could I wouldn't because that'd be quite invasive). uBlock uses a transparent gif while I redirect to a transparent png, so essentially both do the same.

**Comment by isaaclw** [comment]
Could you coordinate with ublock to see if redirecting to the same location causes the error to go away?
