### ISSUE TITLE
Scripts without protocol fail to load

### ISSUE THREAD

**Issue by MattMS** [andryou/scriptsafe#110]
Visit https://baconjs.github.io/.
Open dev tools, get `Failed to load resource: net::ERR_BLOCKED_BY_CLIENT` for https://codeorigin.jquery.com/jquery-2.1.1.min.js.

The source is `<script src="//codeorigin.jquery.com/jquery-2.1.1.min.js"></script>`.

This resource is not appearing in the ScriptSafe popup, but the icon does have an indicator showing that 1 item has been blocked.

Visiting https://jquery.com/ and trusting the domain allows the site to work.

**Comment by SpiralBrad** [comment]
Seconding this. Seeing issues on SO many sites that cause ScriptSafe to show a blocked indicator, but nothing in the UI to allow/distrust said blocked resource. Ruins the extension usage.

**Comment by steelfly33** [comment]
Same occurs with Twitter.  Doing what @MattMS said and then adding **.twimg.com to the whitelist works, but this is not available in the UI.

**Comment by andryou** [comment]
I've released a beta version of v1.0.8.5 which incorporates a fix for this issue: #140. Feel free to test and confirm.

**Comment by andryou** [comment]
v1.0.8.5 which contains a fix for this has officially been released.
