### ISSUE TITLE
Broke site

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [andryou/scriptsafe#112]
Right off the bat your script blocked a site from functioning.
http://filehippo.com/ 

At the very top of the page, I can't choose between Windows, Mac, Web Apps, News.
I wasted time messing with the settings and never could get the links to work.
As soon as I uninstalled ScriptSafe it worked again.

**Comment by peterlaws** [comment]
I can, with and without allowing the domain....

**Comment by GitTheHellOutaHere** [comment]
Huh, don't know what else to say.
Worked before and after the extension, but not with.

One of those unexplained mysteries I guess.

**Comment by andryou** [comment]
Sorry, just catching up on issues and going through. I cannot reproduce this either; I checked the source code and they are ordinary <a> links.
