### ISSUE TITLE
Question about "disable and remove" option

### ISSUE THREAD

**Issue by lordgordon** [andryou/scriptsafe#114]
Hi there,

I had some trouble blocking unwanted contents with ScriptSafe, specially Google's analytic code. My current settings are strict, particularly :
- Disable and remove: `SCRIPT, OBJECT, EMBED, IFRAME, APPLET, AUDIO, VIDEO`;
- Paranoia mode: `enabled`;
- Block Unwanted Content: `enabled`;
- Unwanted Content Mode: `enabled`;
- Remove Google Analytics (UTM) Tracking: `enabled`.

_(full settings listed below)_

This works as expected. Unfortunately this setup make really difficult to use some sites with a lot of javascript hardcoded internally in the HTML (within `<script>` tag). If I disable the `SCRIPT` option, those sites start working, yet all the external Javascript resources dynamically loaded inside a `<script>` are loaded too, without being blocked by ScriptSafe. This includes Google Analytics code, such as`https://www.google-analytics.com/ga.js` and `https://www.google-analytics.com/analytics.js`. 

Steps to reproduce:
1. with the strict settings provided, try to load a page that has Google Analytics code (es: [https://www.theguardian.com/international](https://www.theguardian.com/international)) and monitor the network traffic;
2. `https://www.google-analytics.com/analytics.js` is correctly blocked;
3. now disable `SCRIPT` from "General Settings, Disable and Remove" (and only this option);
4. reload the same page and monitor the network traffic. Now `https://www.google-analytics.com/analytics.js` is loaded (HTTP 200).

Please note that this happens even if the page is not whitelisted. I'm expecting to being able to load internal page scripts while unwanted resource are blocked, even if dynamically loaded.

I'm misunderstanding the way ScriptSafe is supposed to work, or is this a bug?

Thanks for your help.

Regards

**My ScriptSafe settings (black and white list removed for clarity):**

```
annoyances|true
annoyancesmode|strict
antisocial|true
applet|true
audio|true
audioblock|true
battery|true
canvas|false
canvasfont|false
classicoptions|false
clientrects|false
clipboard|false
cookies|true
domainsort|true
embed|true
enable|true
frame|false
gamepad|true
hashchecking|true
iframe|true
image|false
keyboard|false
linktarget|off
mode|block
noscript|false
object|true
optionslist|false
paranoia|true
preservesamedomain|false
rating|true
referrer|true
referrerspoof|off
refresh|true
script|true
sync|true
syncenable|true
syncfromnotify|true
syncnotify|true
tempregexflag|true
timezone|false
uaspoofallow|true
updatenotify|true
useragentspoof|off
useragentspoof_os|off
utm|true
video|true
webbugs|true
webgl|true
webrtc|disable_non_proxied_udp
webrtcdevice|true
xml|true
```

**Comment by andryou** [comment]
Hi @lordgordon,

What you described is the intended behaviour of ScriptSafe. If you untick "SCRIPT" in Options, ScriptSafe's JavaScript capabilities are disabled.

One option you may be interested in is the "Respect Same-Domain" option under Behaviour Settings. Setting this to Strict or Loose will allow inline scripts to run while still blocking unallowed external scripts.

I hope this helps.

With "SCRIPT" enabled, visit https://www.theguardian.com/international and Allow the theguardian.com in the ScriptSafe toolbar panel. The page will refresh and you'll see that inline scripts are allowed to execute and that the google-analytics.com external script is blocked.

If
