### ISSUE TITLE
Prevent Clipboard Interference causes formatting problems in Google Groups post editor

### ISSUE THREAD

**Issue by pointyointment** [andryou/scriptsafe#115]
With Prevent Clipboard Interference enabled, some of the post formatting tools on Google Groups don't work correctly. I've noticed the following so far, but there are probably more:
- The quote button always makes the first paragraph of my post a quote, not the paragraph the cursor is in, as it should.
- The text size menu has no effect.

When I noticed these symptoms, I looked at ScriptSafe and it said it was blocking something like 56 clipboard interferences, so I suspected that the code the Google Groups editor uses for text formatting was being detected as clipboard interference.

Disabling ScriptSafe (from within the extension) and turning off Prevent Clipboard Interference both work to let these formatting tools work correctly, but I'd like to have them enabled on other sites.

If there was an option to disable Prevent Clipboard Interference on specific sites, I'd use that. I'd even use an option to disable ScriptSafe entirely on certain sites, because my other blocking extensions would still work on Google Groups. (I have a few other blocking extensions installed and I left them all active during testing. None of them seemed to cause any problem. If you cannot reproduce, I'll try ScriptSafe on its own, in case it's caused by multiple extensions interacting.)

**Comment by pointyointment** [comment]
Since disabling Prevent Clipboard Interference, I have found I can successfully change the colors of my Gmail labels again. I'd been wondering why that wasn't working at all. I could go into the color menu, but clicking on the swatches had no effect. I turned it back on to confirm: yes, it breaks the color change feature.

**Comment by andryou** [comment]
v1.0.8.5 which contains a fix for this has officially been released.

You are now able to disable each Fingerprint Protection option on a per-site basis :)
