### ISSUE TITLE
us2.campaign-archive1.com (email in browser) doesn't render pictures properly

### ISSUE THREAD

**Issue by isaaclw** [andryou/scriptsafe#116]
here's an example website:
http://us2.campaign-archive1.com/?u=7c55dbbfa32e541749065a92a&id=c2a59c17a0&e=2a1b2e2661

I can't figure out settings with SafeScript that renders the pictures, other than disabling the plugin.
If there was a way to Disable the plugin just on this domain, that would be nice.

**Comment by andryou** [comment]
v1.0.8.5 has officially been released. Could you please retest (once you verify that ScriptSafe v1.0.8.5 is installed) and let me know if the issue is still present? Thanks!

**Comment by isaaclw** [comment]
Thanks. Sorry I missed this.

I'm using 1.0.8.5, and it's still not rendering the pictures.

The option to disable the plugin only for specific domains doesn't seem possible yet. I'm not sure why the javascript that is needed to render the pictures isn't listed in the dialog.

**Comment by andryou** [comment]
Thanks for re-testing!

I managed to find the cause: mailchimp.com is classified as an unwanted content provider and exists in the blocklist. In the next release I will remove it.

**Comment by andryou** [comment]
Mailchimp has been removed from the blocklist as of v1.0.9.0 :)
