### ISSUE TITLE
Microsoft.com Sign In

### ISSUE THREAD

**Issue by rykel** [andryou/scriptsafe#118]
I cannot use microsoft.com with my signed in Microsoft Account, until and unless I totally disable ScriptSafe. Please help?

**Comment by downlz** [comment]
yeah same here.I was working initially after trusting the source but it's no longer working after the sync.

**Comment by andryou** [comment]
v1.0.8.5 has officially been released. Could you please retest (once you verify that ScriptSafe v1.0.8.5 is installed) and let me know if the issue is still present? Thanks!

**Comment by flex-lm** [comment]
I think that #163 could be related to problems on the Microsoft website.

**Comment by flex-lm** [comment]
The Microsoft website (including log in functionality) is now working on my end with version 1.0.9.1

**Comment by andryou** [comment]
@flex-lm thanks for testing! I've also tested and was able to log in and navigate some pages. I'll close this but will be happy to re-open if Microsoft isn't working for others.
