### ISSUE TITLE
Blocked hidden, can't allow them

### ISSUE THREAD

**Issue by D0nR4nd0m** [andryou/scriptsafe#123]
When I open a site, and allow it the page works only partially (this is normal)

But when I refresh the page, there flashes very quickly 9 (red box) and then it counts down to 2 in a blink of an eye. And the page doesn't work properly (since some things get blocked)

Only way to work around this is to allow ALL scripts globally (effects all pages), which raises the question: What's the point of scriptsafe is ALL scripts have to be allowed ??

Just as example quote link on forum does not work on the page, since some script is blocked

This is kind of a bummer, since this all happened after a fresh instal (didn't have issues earlier)

**Comment by D0nR4nd0m** [comment]
Adding to that: Can't even get the logout panel from github without first disable scriptsafe, then enable it again.

only after that it shows the blocked items

**Comment by D0nR4nd0m** [comment]
0k, today re-produced the issue.

Changing one setting in the fingerprint protection did it all. Today it was "battery fingerprinting", yesterday it was some other fingerprinting option

After enabling the option, many pages stopped functioning properly, and disabling does not reverse the effect.
Even after disable block fingerprinting -> reboot PC, still not working.

Only way to reverse the block fingerprinting is to disable scriptsafe completely

**Comment by andryou** [comment]
I've released a beta version of v1.0.8.5 which incorporates a fix for this issue: #140. Feel free to test and confirm.

**Comment by andryou** [comment]
v1.0.8.5 which contains a fix for this has officially been released.
