### ISSUE TITLE
Says it's blocking stuff, but not showing what it's blocking

### ISSUE THREAD

**Issue by spamgirl** [andryou/scriptsafe#127]
I totally started from scratch with the extension so that pages would load more quickly, but now I can't get it to work on many sites I use. It shows that something is being blocked, but doesn't show what nor allow me to unblock it. Here is a screenshot of an example: https://flic.kr/p/NbkmDQ

**Comment by gashtaan** [comment]
+1

Few days ago lot of webs have stopped working, ScriptSafe blocks requests, but there is no way to show or unblock them.

**Comment by snowbound** [comment]
Reason why I stopped using this extension. Websites would not work properly, the extension would be blocking something but never show it in its UI but when the extension was disabled the site worked fine. Went to another extension less frustration.

**Comment by asuh** [comment]
Have any of you tried clearing everything out for that page and only using "Allow" instead of "Trust"?

I've experienced this issue but I also pair this with uBlock Origin so I can often tell what's going on there and can resolve the issue. Sometimes you just have to start over on that page.

**Comment by snowbound** [comment]
When I using the extension I rarely used Trust but rather used Allow on 99% of the websites. The extension would show no blocked scripts yet the page would not display. Yes I am using Ublock origin and would get that warning for interaction between ScriptSafe and UBlock Origin. 

I have yet to see this issue when using the other script blocking extention in Chrome.

**Comment by AykutCevik** [comment]
I have the same issue which is really annoying cause you can't get the site work and must switch the browser or disable the extension at all.
I allowed [this](https://pstadler.sh/battery.js/) site temporarily and I could not allow any other blocked sites:
![image](https://cloud.githubusercontent.com/assets/1965251/19862346/32186452-9f90-11e6-87a0-2d6d6e1b25a2.png)

But as you can see in the badge of the extension icon there are still blocked elements. 

Looking into the dev console, I can see that the following request is blocked:
`GET https://rawgithub.com/pstadler/battery.js/master/battery.js net::ERR_BLOCKED_BY_CLIENT`
  
Opening the file and allowing it temporarily did not change anything. 

I hope this will help. Thank you for your great extension btw.

**Comment by spamgirl** [comment]
@asuh - I ended up completely deleting and reinstalling the extension, removing all of my permissions and starting from scratch. I still had the same problem - I even tried allowing, but that didn't help. What DID help was that I clicked around the website until I began to be presented with more options to trust, which I did until the issue went away.

**Comment by OmgImAlexis** [comment]
This happens on 1/10 sites I visit.
![screen shot 2016-11-17 at 9 17 39 am](https://cloud.githubusercontent.com/assets/6525926/20369039/c8cb643a-aca6-11e6-98c1-d4e47265faf5.png)

**Comment by snowbound** [comment]
OmgImAlexis seen the same behavior here which forced me to disable the extension. Then I forget the extension is disabled so what use is a script blocking extension if we have to turn it off and on again. That is why I got frustrated with it.

**Comment by OmgImAlexis** [comment]
@andryou can we please get an update on this?

**Comment by spamgirl** [comment]
What you can do is inspect the page (ctrl-shift-I) and look for the elements that have been blocked. Go to those URLs and manually block/allow those domains.

**Comment by AykutCevik** [comment]
@spamgirl didn't work for me in some cases.

**Comment by war59312** [comment]
Same issue here. What a shame. Was a great extension, but seems dead now. See https://github.com/andryou/scriptsafe/issues/128

To work around this problem, I simply look at the source code of the page.

I spend a minute or two, normally less, figuring out which domain(s) are missed (still blocked).

**Comment by ortreum** [comment]
same on angular.io too. i can not unblock cdn.firebase.com.

**Comment by andryou** [comment]
Thanks for the report and examples. I was able to reproduce this and this will be my main focus. Will comment again with any updates.

**Comment by asuh** [comment]
Great to see you on here again! If you need anymore examples, go to https://trello.com/ as a logged in user. Same experience for me.

**Comment by andryou** [comment]
Just committed an update to this repo that works consistently in my testing; will continue to test it.

**Comment by OmgImAlexis** [comment]
Can you please let us know once it's updating in the chrome web store.

**Comment by andryou** [comment]
@OmgImAlexis will do!

I've released a beta version of v1.0.8.5 which incorporates a fix for this issue: #140. Feel free to test and confirm.

**Comment by andryou** [comment]
v1.0.8.5 which contains a fix for this has officially been released.
