### ISSUE TITLE
Referrer Spoof: allow on whitelisted pages

### ISSUE THREAD

**Issue by AykutCevik** [andryou/scriptsafe#129]
The "Referrer Spoof" setting allows currently four values:
- Off
- Same document
- Same domain
- Custom

I would suggest a combination with a checkbox or something similar, which allows whitelisted domains to read the referrer in addition to the setting above. So a whitelisted domain would weight more than the setting above. If its not whitelisted, the setting above would be applied.

This would break less sites like PlayMusic and we could use some of the pages without disabling the extension at all.

**Comment by andryou** [comment]
Thanks Aykut, I noticed that you have the setting set to Enabled by default; I've changed it to Disabled to follow the default for the similar checkbox for User-Agent Spoof.

**Comment by AykutCevik** [comment]
Seems legit. Sorry for the mistake in the js/ss.js :)

**Comment by andryou** [comment]
Beta version of v1.0.8.5 available in #140, feel free to test and confirm :)

**Comment by AykutCevik** [comment]
@andryou nice work, thank you! :)
"Referrer Spoof"-option on whitelisted pages is now working, so I can play music on Google Play without errors and works as expected on a disabled page like https://www.whatismyreferer.com/.
But I'm missing the setting checkboxes as I postet in [#140](https://github.com/andryou/scriptsafe/issues/140#issuecomment-267812623).

A lot of work done in a few days, awesome!

**Comment by andryou** [comment]
Thanks again!
