### ISSUE TITLE
Stopped working after update (1.0.7.2, OSX 10.11.5, Chrome 50.0.2661.102 (64-bit))

### ISSUE THREAD

**Issue by exoduz** [andryou/scriptsafe#13]
Hi Andrew,

Firstly thanks for the great work on this.

I've recently updated to the latest version but ScriptSafe seems to have stopped working.

It no longer shows the scripts and I can't seem to control any of the pages. Not really sure what's up but would really appreciate it if you can take a look at it.

<img width="625" alt="screen shot 2016-06-01 at 6 04 04 pm" src="https://cloud.githubusercontent.com/assets/4537316/15705782/4459a1ba-2823-11e6-8f68-5d5140321784.png">

**Comment by exoduz** [comment]
Updated Chrome to version 51.0.2704.63 (64-bit) but it's still not working.

**Comment by andryou** [comment]
Did you try restarting your browser?

**Comment by exoduz** [comment]
Yes, restarted browser and computer.

**Comment by exoduz** [comment]
Not really sure but I uninstalled, then reinstalled it. Seems to be working fine. Trying to get all my settings back now.

**Comment by andryou** [comment]
Very strange, I'll keep this issue open. If you or anyone else experiences this issue, please right-click in the panel, click on Inspect, click on the Console tab, and copy and paste the contents here :) (and thanks for you kind words! Sorry I was on the train)

**Comment by exoduz** [comment]
Yeah. It's really strange. Not really sure what it is either. Arrgghh you should've told me that earlier, I could've debugged something but now that it's working I can't see any errors.

Thanks for all the hard work. I've been using ScriptSafe for a few years now and it's been great! Keep up the good work!

**Comment by andryou** [comment]
Thank you! I haven't heard from users yet on how they're finding the new versions: do you notice any speed improvements?

**Comment by exoduz** [comment]
I found the loading of the dropdown is faster, the animation is also smoother.

In the older versions, there'd be times that when I click the ScriptSafe button that it would open like the above screen shot. And then I'd close it, reopen it and the dropdown would be just fine. This issue has not happened with the new version just yet.

Another thing I just found that you might want to have a quick look is the animation. If I go to a never before opened website and no scripts are running, the dropdown opens from the top right -> bottom left. This only happens on the first load. After that it loads from top -> bottom.

Hope this helps.

**Comment by andryou** [comment]
The first issue you mentioned was relates to #4, which I've (hopefully) addressed in the latest version :)

In the second point you mentioned, does it fully open?

**Comment by ROpdebee** [comment]
Just gonna chip in here as well: I didn't get the original issue after the update but that might be because it's updated straight to 1.0.7.3. The popup animation changing also happens to me but much more frequently (and yes, it does open fully). I get it about 25% of the time sliding diagonally and the other 75% vertically. Again as with issue #4 this is not limited to just ScriptSafe, other extensions do this as well.

**Comment by exoduz** [comment]
@andryou Yes, it fully opens fully not like in #4.

**Comment by andryou** [comment]
I'm going to close this issue since the newest versions include checks to prevent this scenario (and just to keep the issues page tidy).

**Comment by exoduz** [comment]
@andryou Thanks for all your hard work! :)
