### ISSUE TITLE
whitelisted chase domain but says javascript is disable

### ISSUE THREAD

**Issue by etaitingi** [andryou/scriptsafe#134]
I whitelisted **.chase.com but it says my javascript is disable. Is this a bug?

**Comment by andryou** [comment]
This may be related to the bug where not all blocked resources are actually listed in the ScriptSafe panel. I'll be releasing v1.0.8.5 by end of this week and hopefully you can re-test afterwards!

I'll leave this issue open.

**Comment by andryou** [comment]
v1.0.8.5 has officially been released. Could you please retest (once you verify that ScriptSafe v1.0.8.5 is installed) and let me know if the issue is still present? Thanks!

**Comment by etaitingi** [comment]
No dice. I checked that I have the updated to 1.0.8.5 version.

**Comment by asuh** [comment]
This could be related to a similar problem I had using uBlock Origin.
https://github.com/gorhill/uBlock/issues/1816

**Comment by etaitingi** [comment]
Unfortunately, I had that already. I whitelisted **.chase.com but I am still getting the error.

http://imgur.com/P2vZJSH -> whitelist
http://imgur.com/EpdzmFk - >error

**Comment by asuh** [comment]
Did you try adding just `chase.com` without the star selectors? See if that works.

**Comment by dz67jam** [comment]
it could be the chase pages here that are blocked 

https://safetechpageencryption.chasepaymentech.com

**Comment by etaitingi** [comment]
This issue seems to have disappear. This was before the update on 1/18. Might be an issue on chase side.. sorry folks for not finding out the root cause.

**Comment by andryou** [comment]
@etaitingi thank you for following up and I'm very happy to hear that the issue is gone for you.
