### ISSUE TITLE
'Block Device Enumeration' doesn't work

### ISSUE THREAD

**Issue by DocumentRoot** [andryou/scriptsafe#135]
Hi
using this demo nothing changes with Block Device Enumeration enabled
https://browserleaks.com/webrtc

It seems that ScriptSafe blocks only old way enumeration using MediaStreamTrack, but not MediaDevices https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices

**Comment by andryou** [comment]
Hi, I've release a beta version of v1.0.8.5 which incorporates a fix for this issue. Feel free to test and confirm :) #140

**Comment by andryou** [comment]
v1.0.8.5 which contains a fix for this has officially been released.
