### ISSUE TITLE
Handling noscript tag

### ISSUE THREAD

**Issue by DocumentRoot** [andryou/scriptsafe#136]
When ScriptSafe blocking JS, it doesn't disable JS, it only blocks execution of found scripts. I understand correctly? So &lt;noscript&gt; tag  is not processed...

```
<noscript>This is &lt;noscript&gt;</noscript>
<script>document.write('This is &ltscript&gt;');</script>
```
I will not see any of those lines.

ScriptSafe also has option to "Disable and Remove: &lt;NOSCRIPT&gt;", but hm, why is it necessary if noscript never executed.

**Comment by andryou** [comment]
If JS is blocked, then Chrome will run HTML contained within &lt;noscript&gt; elements (which sometimes contain tracking workarounds such as loading webbugs).

If that option you mentioned is enabled, then the entire &lt;noscript&gt; element will be removed, preventing any HTML within it from executing.

**Comment by Steven--** [comment]
This doesn't match my observations. For example in the following page I only see the first paragraph even if the <nostript> elements are not blocked.
  
https://terrillthompson.com/tests/noscript.html

**Comment by andyexeter** [comment]
I get the same results as @Steven--:

Disabling JavaScript through Chrome settings > Show advanded settings > Content settings > "Do not allow any site to run JavaScript" shows the `<noscript>` tag. 

Enabling JavaScript through Chrome settings as above and enabling ScriptSafe with the "Disable and remove" checkbox for `<noscript>` does _not_ show the tag.

**Comment by imgurbot12** [comment]
I am also having the same issue.
