### ISSUE TITLE
Allow All Blocked For Session should only need to be clicked once

### ISSUE THREAD

**Issue by giantsloar** [andryou/scriptsafe#138]
When I click "Allow All Blocked For Session" it should load everything, and not require me to repeatedly click the "Allow All Blocked For Session" button after every reload until the page displays properly.

**Comment by andryou** [comment]
Unfortunately it's not possible to avoid this; ScriptSafe doesn't know what to block until the item is loaded. In other words, a temporarily allowed script which was previously blocked may refer to a resource on another domain, which was unknown up until the script was allowed.
