### ISSUE TITLE
WebRTC blocking breaks AWS console

### ISSUE THREAD

**Issue by MarkRose** [andryou/scriptsafe#14]
The new WebRTC feature breaks using the AWS console. Having it enabled causes lots of refreshing. All the relevant domains for JavaScript are enabled.

**Comment by andryou** [comment]
Thanks for the report, maybe I'll change it to be off by default.

If you set it to off, does AWS work?

**Comment by MarkRose** [comment]
Actually, it looks like it's AWS having trouble: http://status.aws.amazon.com/

I'll close. Thanks for the excellent extension though!

**Comment by andryou** [comment]
Good to hear it's something on their end, thanks for following up!
