### ISSUE TITLE
v1.0.8.5 Beta 2 - Testing

### ISSUE THREAD

**Issue by andryou** [andryou/scriptsafe#141]
I'm imposing a code-freeze on myself as I know it's not good practice to introduce major features during beta testing (my apologies; I was on a roll today and coding the granular Fingerprint Protection whitelisting feature (point 2 below) went very well).

The code freeze means only bug fixes will be made, mainly focusing on the points below if there are any issues: no new features will be introduced.

**What's changed from v1.0.8.4 to aid in beta testing (feel free to view referenced issues below for test cases):**

<ul>
							<li>Resolved issue where blocked items were sometimes not being listed in the panel</li>
							<li>Added the ability to selectively disable Fingerprint Protection on a per-domain, per-option basis</li>
							<li>Added more control over Referrer Spoofing (thanks AykutCevik)</li>
							<li>Improved Block Device Enumeration to block mediaDevices.enumerateDevices()</li>
							<li>Made Battery Fingerprint Blocking more compatible with sites (thanks TjWallas)</li>
							<li>Included translations for 13 new languages: Chinese - Simplified, Chinese - Traditional, Czech, Dutch, French, German, Hungarian, Italian, Korean, Latvian, Romanian, Russian, and Swedish (thanks to all translators listed at the bottom of the Changelog and Options pages)</li>
							<li>Improved syncing of existing rules if upgrading from a pre-v1.0.7.0 instance</li>
							<li>Added a reload icon to the panel</li>
							<li>Updated unwanted content providers list</li>
							<li>Updated available Operating System and Browsers for User Agent spoofing</li>
							<li>Resolved minor issue with Referrer Spoof and User-Agent Spoof options display</li>
							<li>ScriptSafe is now released under the GNU GPLv3 license</li>
                        </ul>

**Instructions on how to Beta Test:**
1. Download the v1.0.8.5 BETA 2: **https://github.com/andryou/scriptsafe/releases/download/v1.0.8.5_beta2/ScriptSafe_v1.0.8.5_Beta_2.zip**
2. Extract the ZIP file to its own folder anywhere on your computer
3. Copy and paste **chrome://extensions** into your browser address bar and press Enter
4. Make sure you have disabled the Chrome Web Store version of ScriptSafe (ID: oiigbmnaadbkfbmpbfijlflahbdbdgdf)
   - Note: you may want to save a copy of your existing ScriptSafe settings at this point (see https://www.andryou.com/scriptsafe/frequently-asked-questions/#backup)
5. Enable “Developer Mode“
6. Click on **Load unpacked extension**, navigate to the folder you extracted ScriptSafe to in step #2 and click on OK
7. Restore your existing ScriptSafe settings: https://www.andryou.com/scriptsafe/frequently-asked-questions/#restore

**Any feedback/issues, please add it as a comment here or reply to my email I sent to all beta testers. If everything looks good, please let me know as well!**

Thank you!

**Comment by andryou** [comment]
Screencap of the ability to selectively disable Fingerprint Protection on a per-domain, per-option basis in the panel (labels are click to toggle):

![2016-12-19_23-43-16](https://cloud.githubusercontent.com/assets/4351175/21338543/36fba854-c645-11e6-9712-556a55f0d3c8.png)

**Comment by asuh** [comment]
This is likely my ignorance but I enabled Fingerprint Protection on both Blank and Block but EFF still shows that I have a unique fingerprint: https://panopticlick.eff.org

I also had all the boxes checked in Fingerprint Protections options tab in the settings. I'm assuming this feature is supposed to show that I should not be unique, right?

**Comment by AdamF001** [comment]
@andryou  Everything looks good in the Hungarian Translation part, tested fingerprint and got the same result as @asuh .

**Comment by andryou** [comment]
Fingerprint Testing is a bit tricky because it's based on data collected from other users, and the majority of users likely don't use script blockers. Therefore using ScriptSafe to protect against sites from enumerating your devices and other vectors will cause you to appear "unique" compared to the vast majority.

This is a topic which is relevant to the Tor Browser: "should I enable NoScript or not?" Enabling it does make your fingerprint unique, but it also protects you against 0-day attacks (and from sites tracking you).

**Comment by andryou** [comment]
Just a note: I'm hoping to officially release v1.0.8.5 before the end of this week (in time for Christmas), so I'll wait a bit longer for people to test and report any issues. I'll assume that no news means good news!

**Comment by gameb0y** [comment]
@andryou hello Andry

audiocontext not fully blocked :/ please fix!

![untitled](https://cloud.githubusercontent.com/assets/19530450/21407856/898a03ba-c7c9-11e6-8100-33219256873f.jpg)

**Comment by andryou** [comment]
@gameb0y good news:

![2016-12-21_18-05-00](https://cloud.githubusercontent.com/assets/4351175/21409418/280e489c-c7a8-11e6-8c0b-7f08b1e02b2f.png)

**Comment by gameb0y** [comment]
@andryou thanks bro.

I get two error messages with Opera Browser

![1](https://cloud.githubusercontent.com/assets/19530450/21422247/bd8d134a-c82e-11e6-800d-c55f5c3fa422.jpg)

![2](https://cloud.githubusercontent.com/assets/19530450/21422255/c84bc3b2-c82e-11e6-894b-34d10be1f344.jpg)

**Comment by AdamF001** [comment]
@andryou I have found another might be error whenever I visit http://beta.speedtest.net/ or something that has to do with the network ScriptSafe freaks out and does not let me change anything within. Pictures below with console.
![what](https://cloud.githubusercontent.com/assets/24633575/21424409/9fce574a-c83a-11e6-9d4f-db781815ce22.png)
![whatt](https://cloud.githubusercontent.com/assets/24633575/21424412/a340531a-c83a-11e6-8c46-33e658342de4.png)
![console](https://cloud.githubusercontent.com/assets/24633575/21424414/a5108c32-c83a-11e6-8d2b-49e02a79e82f.png)

**Comment by andryou** [comment]
@gameb0y thanks; I'll resort to hard-coding the version numbers instead of doing an AJAX pull of the manifest.json. I'll also look into publishing ScriptSafe on the Opera Web Store.

@AdamF001 thank you! I caught that in my testing and already committed a fix. I'm very happy you're giving Beta 2 a thorough drive! It occurred when you have <NOSCRIPT> blocking enabled: https://github.com/andryou/scriptsafe/commit/4183283e6e7246c6f8c265e1f00dfc6ec9c79804

**Comment by AdamF001** [comment]
@andryou I have found another maybe misbehaviour when trusting a site it automatically puts most-visited(1) into allowed but it does not show it is allowed. (Windows 7 x64, Google Chrome 55 x64), attached console as well. 

![allow](https://cloud.githubusercontent.com/assets/24633575/21449708/00048e92-c8e8-11e6-85bc-c96ace71c60b.png)
![allowed](https://cloud.githubusercontent.com/assets/24633575/21449709/0235c3ca-c8e8-11e6-98f6-19dac7b1e827.png)

**Comment by AdamF001** [comment]
@andryou Found that Spoofing Windows 98 with IE 11 does not spoof it correctly (shows Mozilla with win98) (Windows 7 x64, Google Chrome 55 x64)
![useragent](https://cloud.githubusercontent.com/assets/24633575/21450055/5c0fc122-c8eb-11e6-8e5b-b6ff79a70e87.png)
![useragenttest](https://cloud.githubusercontent.com/assets/24633575/21450058/5f5769de-c8eb-11e6-9151-a3ff8fd87b7e.png)
![useragenttesttest](https://cloud.githubusercontent.com/assets/24633575/21450059/60eeeaf6-c8eb-11e6-9c96-7eee7e4cb1a8.png)

**Comment by AdamF001** [comment]
@andryou Tested TimeZone Spoof with browser restarted twice and set to -7UTC and it does not change the browser timezone, it leaves it as it is and no console errors are shown. (Windows 7 x64, Google Chrome 55 x64)
![timezone](https://cloud.githubusercontent.com/assets/24633575/21450149/2d5a577e-c8ec-11e6-9954-c35551c35f2f.png)
![timezonespoof](https://cloud.githubusercontent.com/assets/24633575/21450151/2fce89d0-c8ec-11e6-8039-4954844c3851.png)

**Comment by andryou** [comment]
@AdamF001 thank you! For the "most-visited" entry, it's not appearing in the list because it's not being blocked as it is an internal chrome page ("chrome-search://").

For the user agent, the "Mozila /5.0" portion is correct: https://www.sitepoint.com/ie11-smells-like-firefox/

![2016-12-23 10_09_04](https://cloud.githubusercontent.com/assets/4351175/21456780/94f17f3c-c8f8-11e6-8cf6-72f196093472.png)

**Comment by AdamF001** [comment]
@andryou okay, everything else works like charm good job on making such an amazing extension!

**Comment by andryou** [comment]
v1.0.8.5 has been pushed to the Chrome Web Store and should be deployed shortly.

Github releases:
* **Web Store** version: https://github.com/andryou/scriptsafe/releases/tag/v1.0.8.5
* **Legacy** version (no "Privacy" permission => no WebRTC protection): https://github.com/andryou/scriptsafe/releases/tag/v1.0.8.5_leg

Thank you everyone for your time, patience, and support in this release :)

**Comment by asuh** [comment]
I'm still running Beta 2 in Chrome Canary and trying to use https://play.spotify.com/settings. I enabled only ScriptSafe in Incognito mode. For some reason, I cannot "Allow" or "Trust" all the scripts on the page and so the web player doesn't completely load.

Can anyone else verify this?

**Comment by andryou** [comment]
@asuh could you please backup your settings, install this (https://github.com/andryou/scriptsafe/releases/download/v1.0.8.5/ScriptSafe_v1.0.8.5.zip) and try again?

**Comment by asuh** [comment]
Thanks for the quick reply, @andryou. So this stable 1.0.8.5 changed it to work again. That said, there's still some scripts that I cannot "Allow" or "Trust". I think they're called *.spotilocal.com. Maybe they aren't essential to the playback of the web app but either way I can't seem to whitelist them.

**Comment by andryou** [comment]
@asuh great to hear it works with the stable release! I'll try to investigate this over the weekend.

**Comment by asuh** [comment]
@andryou It appears that enabling Canvas Fingerprint Protection also breaks Spotify web player, so double whammy with Spoofed Time Zone.
