### ISSUE TITLE
Cannot change language

### ISSUE THREAD

**Issue by uxlapogi** [andryou/scriptsafe#145]
The latest update changed my Scriptsafe language and I cannot change it back to english.

**Comment by andryou** [comment]
Please see this page for instructions on how to change it back to English: https://developer.chrome.com/extensions/i18n#win-ui

The Windows instructions on that page are outdated, below are steps that seem to work with the latest Chrome version:

1. App icon > Options
1. Click on Show advanced settings at the bottom of the page
1. Scroll down to Languages
1. Click on the "Language and input settings..." button
1. Use the drop down to set the Google Chrome language
1. Make sure English is first in the list
1. Restart Chrome

**Comment by uxlapogi** [comment]
Thanks for your very prompt response and sorry for opening an issue on this here, I wasn't aware I still had chrome set to a different language and assumed the issue being with your extension.

**Comment by andryou** [comment]
No worries at all! All the best to you and your family over the holiday season.

**Comment by m32po** [comment]
Hi, same problem here: Chrome browser set to Italian language and ScriptSafe 1.0.8.5 now also in Italian. However I was happy with ScriptSafe in English and Chrome in Italian. So in order to change ScriptSafe back to English the only chance I have is to change Chrome interface language, isn't it? Or is there the possibility to change the ScriptSafe language only?

**Comment by trou** [comment]
Same as m32po here, the UI design is completely broken in French.

**Comment by andryou** [comment]
@m32po I looked for workarounds but unfortunately the Chrome extension API only allows me to get the UI locale and not set it.

@trou thanks for the report, I am working on redesigning the ScriptSafe panel to better accommodate all locales and ensure the buttons are not cut off. I've received several reports of the Russian and German locales having issues where buttons in the panel are going beyond the width of the panel.

**Comment by m32po** [comment]
I must confess I have the same problem as @trou. With ScriptSafe localized to Italian, some UI buttons break the layout. I attached a couple of screen snips. But it isn't a big issue for me now, I set Chrome to English as a workaround.

![snip1](https://cloud.githubusercontent.com/assets/1173018/21914077/1a53e7f8-d931-11e6-85e7-70520e25e69b.png)
![snip2](https://cloud.githubusercontent.com/assets/1173018/21914084/225526a6-d931-11e6-908b-e245159e57a2.PNG)

**Comment by andryou** [comment]
@m32po thanks for the screenshots! Here's my solution to it that I'm currently working on - changing it from a two-column layout to one-column:

![2017-01-12_22-02-48](https://cloud.githubusercontent.com/assets/4351175/21917068/084f4eee-d913-11e6-8943-9b7c53a881ea.png)

Another benefit of this is that the Options, Refresh, and Close buttons are now easily accessible and all the domain control buttons match up.

**Comment by uxlapogi** [comment]
I'm always in favor of options: maybe add a radio button to display your extension in english no matter the actual locale of the browser, something like "use browser locale [ ] use english [x]"?

**Comment by andryou** [comment]
@uxlapogi I am the same and would have loved to provide that option to users, but unfortunately there is no way to have ScriptSafe dynamically set the user's desired locale as the most I can do is just retrieve locale-related data and not for example set the locale to be "en", "it", etc: https://developer.chrome.com/extensions/i18n#methods

Because of this, I've decided to redesign the panel. I will be posting the beta here within the next day or two.

I believe I managed to fix the issue where the panel scrollbar sometimes won't scroll as well.

**Comment by andryou** [comment]
v1.0.9.0 Beta has been posted for testing :) #153

**Comment by m32po** [comment]
@andryou Italian locale seems to be working fine now. The one column layout solution is better than two columns one, it is more consistent, now also the primary domain is aligned to the left with the others and it has the rating button as well. God job!

**Comment by uxlapogi** [comment]
@andryou I think you misunderstood what I proposed. I don't want you to **set** the locale of the browser, I want you to add an option to completely **ignore** it, so that there are essentially two locale: the browser and the _extension locale_.

Ideally that would mean the four functions you linked are only there to propose the initial language like 'hey there, you are starting scriptsafe for the first time, I set the locale for this extension to the same one as your browser, do you want to change it to something else so you can view this extension in spanish on a french browser on a spanish windows?'
That would be so great. :(

Because usually what happens with this auto detect stuff on websites is 'Hey there, I see you have an english windows, an english browser, set your language preferences to english and explicitly requested to view this website in english but screw you! You are requesting this page from a german IP so here is an auto translated mess that will give your grandchildren cancer in their graves. Have a nice day!'

I am using a couple of extensions that are only available in english. That doesn't mean they don't work when I live in Mongolia, it just means it's in english, because they are hardcoded in english. (They are my favorite actually, since we are already at 12 comments now and the whole thing would've never happened in the first place. *wink But I understand if someone wants to use their mother tongue.)

**Comment by m32po** [comment]
@andryou I agree with @uxlapogi, the possibility to set ScriptSafe locale ignoring browser locale it could be useful. The one column layout is a very good improvement but doesn't answer what @uxlapogi asked with the issue #145 in the first place, that is "_Cannot change language_", more precisely "_I cannot change the ScriptSafe language ignoring the browser one_". I hope I understood correctlty what @uxlapogi asked, so I tweaked a little bit of HTML code and I took these two snips to get an idea of what could be a ScriptSafe Language option, based on what are the ScriptSafe locales available now:

**Language option closed**
![language-option-snip01](https://cloud.githubusercontent.com/assets/1173018/21955332/737c247e-da69-11e6-918f-4c8d2eba4683.PNG)

**Language option opened**
![language-option-snip02](https://cloud.githubusercontent.com/assets/1173018/21955333/77989844-da69-11e6-8745-b103ef590723.PNG)

**Comment by andryou** [comment]
Thank you both for your thoughts and input! Over the next couple of weeks
I'll look into the possibility of creating a custom locale parsing system,
overriding the native Chrome chrome.i18n API. This would give me the
ability to allow users to change the language at any time, which the native
API does not.

My current priority is wrapping up beta testing soon to get the improved
panel (and other updates) to all users as soon as possible so that the
panel is usable in all languages.

**Comment by andryou** [comment]
Looks like it was simpler than I thought! The next version will include the ability to change the language, where the change will be immediate. I will continue looking through submitted issues to see what I can fix, then have a public beta testing period for v1.0.9.1.

If anyone is curious, you can download a zip of this repo and load it into Chrome. Relevant commit: https://github.com/andryou/scriptsafe/commit/3e38d403ab1d2c86dd0d70ab37af1b781ff868ef

![2017-01-18 17_57_33](https://cloud.githubusercontent.com/assets/4351175/22086624/a67da370-dda7-11e6-944d-41ae564f4e7b.png)

**Comment by andryou** [comment]
v1.0..9.1 Beta is now available for testing: #163

**Comment by andryou** [comment]
v1.0.9.1 has been published in the Chrome and Opera stores which addresses this issue. Thanks again for your report and testing!
