### ISSUE TITLE
Support for pdf

### ISSUE THREAD

**Issue by PatrickChen83** [andryou/scriptsafe#147]
Open pdf in browser is blocked by default, but if we allow all websites once we want to view the pdf, we miss the point of using ScriptSave, right? So I think it a feature to be added.

**Comment by andryou** [comment]
You are able to temporarily allow the domain to access the PDF (for the current browsing session), and choose to manually revoke this access at any time. This way it doesn't persist across browsing sessions, I hope this helps.

PDF files are a common method of infecting users, so I would be hesitant to add an option to persistently allow PDF files from being allowed: http://www.drchaos.com/distributing-malware-inside-adobe-pdf-documents/

**Comment by stupid-genius** [comment]
The notion of "you can manually manage the settings" only seems sensible in the abstract; it isn't practical. 
 ScriptSafe didn't used to have this PDF blocking behavior and it really should not have been added.  ScriptSafe isn't a "security solution".  The uninitiated have plenty of other vendors for that; ScriptSafe should stay focused on one thing: managing the execution of JavaScript.  If you go down the route of shoving more and more cruft into it, you're going to start losing users (such as myself).

**Comment by pointyointment** [comment]
>http://www.drchaos.com/distributing-malware-inside-adobe-pdf-documents/

404

I'm just one (annoyed) person, but I have never heard of, nor to my knowledge encountered, an infected PDF document on the web.
