### ISSUE TITLE
See Blocked Items ratings in a new tab without closing ScriptSafe popup and without losing focus of current tab

### ISSUE THREAD

**Issue by m32po** [andryou/scriptsafe#148]
Hi, I will try to explain me better. I use ScriptSafe with Chrome. At the moment, in the ScriptSafe popup, if I want to see a domain rating I have to Left-Click the lens icon on the domain's left, then ScriptSafe popup closes and a new browser tab opens and gets focus. I found out I can CTRL + Left-Click the rating button to open the WOT rating page in a new tab without losing the current tab focus. The problem is ScriptSafe popup also closes. Ok, this behavior is fine if I wish to see only one domain's rating. But if I wish to see several domain's ratings at the same time (= open several WOT rating tabs), it would be useful the ScriptSafe popup remains opened, so I can CTRL + Left-Click on every domain listed under Blocked Items section. Now I have to re-open the ScriptSafe popup for every domain's rating.

**Comment by andryou** [comment]
Excellent suggestion. I have coded this functionality and it will be included in the next release!

**Comment by andryou** [comment]
v1.0.9.0 Beta has been posted for testing :) #153

**Comment by m32po** [comment]
Oh yes! Now is a more relaxing domains' rating checking task! Well done!
