### ISSUE TITLE
Use right-click menu to allow scripts in window with no controls

### ISSUE THREAD

**Issue by sethgilchrist** [andryou/scriptsafe#149]
If a website opens a popup window with no extensions bar that is from an URL that is blocked, there is now way to allow that URL.  For example, my company does online trainings and when you press "Start training" on any of the lessons, it opens a new window that has no controls or extensions buttons.  The only way to allow is to manually copy the address to the whitelist, or to disable scriptsafe until I'm done.

If there was a right-click menu, I could allow scripts on the page without the extra steps.  A menu similar to Adguard would be perfect.
![screen shot 2017-01-04 at 2 07 30 pm](https://cloud.githubusercontent.com/assets/4625551/21661163/98d10f9e-d287-11e6-871b-661521c24799.png)

**Comment by andryou** [comment]
Great suggestion, this will be included in the next release. I plan to start public beta testing either tomorrow or after tomorrow!

![2017-01-13_1-25-49](https://cloud.githubusercontent.com/assets/4351175/21920474/4c47cdc6-d92f-11e6-955c-91ab735beafe.png)

(note: ScriptSafe is set to "Block" by default in the above screenshot, so Allow, Allow (Temporary), and Trust are shown. If ScriptSafe is set to "Allow" by default, Block, Block (Temporary), and Distrust will be shown instead).

**Comment by andryou** [comment]
v1.0.9.0 Beta has been posted for testing :) #153

**Comment by andryou** [comment]
v1.0.9.0 pushed to the Web Store, existing instances should auto-update shortly.

**Comment by sethgilchrist** [comment]
Fantastic.  Thanks for the quick work!
