### ISSUE TITLE
Freezes Youtube navigation for 5 seconds

### ISSUE THREAD

**Issue by peterlaws** [andryou/scriptsafe#15]
When you navigate around Youtube, every link you click gives a delay before the red line at the top appears.... When I disable the extension, no delay...

Is this a known issue?

Chrome v51.0.2704.63m
SafeScript v1.0.7.3

**Comment by andryou** [comment]
Unfortunately I can't reproduce this, I wonder if it's some sort of conflict with another extension.

What operating system are you using?

**Comment by peterlaws** [comment]
Win 7 64bit

Just tried disabling my other extensions, same outcome........

I frequent a forum, and I noticed it freezes that too on load.

It's like the tab isn't responding, just not long enough for the usual "kill" popup to appear.... I'm sure it's not that, but it feels like it if you get what I mean.

**Comment by andryou** [comment]
What YouTube-related domains do you have whitelisted?

I have the following whitelisted:
* youtube.com
* google.com
* \*.googlevideo.com
* s.ytimg.com

**Comment by peterlaws** [comment]
All those, yep.

The tab hogs 25% of a CPU compared to 10% with SS disabled.

**Comment by andryou** [comment]
Can you try setting "XML HTTP Request Handling" to Disabled and let me know if this has any effect?

**Comment by peterlaws** [comment]
Still the same....

BTW, I've been using SS for years without trouble, and since the recent updates (ones where you pop the new notice in a tab), this has happened.......

I assume the Export field is the data for everything? I might actually try and uninstall then reinstall and start fresh.

**Comment by andryou** [comment]
That is correct! Before you do, please give v1.0.7.4 a try (pushing it soon)

**Comment by andryou** [comment]
Just letting you know I've pushed v1.0.7.4 and it should auto-update for you soon.

**Comment by peterlaws** [comment]
Still same with .4-6......... Will reinstall SS from scratch later today and get back to you.

**Comment by peterlaws** [comment]
I now think I know why safescript freezes......  If I clear my whitelist...... No freezes..... So, it has to be a parsing issue?  tbh, my whitelist has 2,065 sites in..... That said, this doesn't explain why this is recently happening. Maybe you've changed something?

**Comment by andryou** [comment]
Ah that sounds like that's the cause. I did change the parsing recently to support matching expressions. 

I'll look into a fix. I'll comment here once I figure out something or have something for you to test, but this is a valid issue. Please keep your whitelist handy :)

**Comment by andryou** [comment]
Please try v1.0.7.8 and close this issue if resolved, thanks!

**Comment by andryou** [comment]
(sorry for the delay in getting v1.0.7.8 to you; it's been "Pending Review" in the Chrome Web Store since I pushed it out 8:45pm eastern yesterday)

**Comment by peterlaws** [comment]
Still a delay...

I've started from scratch, adding to the lists all over again... I'm sure I'm not using most the sites I had in there now anyway.... Cheers for trying and expect a donation soon.

**Comment by andryou** [comment]
Thanks for the update :)

I've created a whitelist with 5,000 entries and I'm working on tweaking the lookup ("A" in the screenshot is the current method). I will incorporate the fastest method into a future update once I'm happy with the speed:

![2016-06-07 10_39_55](https://cloud.githubusercontent.com/assets/4351175/15862010/4310cd38-2c9c-11e6-9f11-48f33fa76918.png)

**Comment by andryou** [comment]
Coming in v1.0.7.9 (likely tomorrow):

![2016-06-08 17_22_17](https://cloud.githubusercontent.com/assets/4351175/15911378/b072bf56-2d9d-11e6-8554-45d0a83fb48c.png)

**Comment by peterlaws** [comment]
I'll give it a try.

BTW, hope you got my donation - for your effort on this issue lol

**Comment by peterlaws** [comment]
I was hoping I can say this is now fixed, but there's still a delay :/ Even in incognito mode with all other extensions disabled.

The only other tools I use that block web stuff are Ghostery and Ad-Muncher.

**Comment by andryou** [comment]
I was hoping the same! Has the delay been improved in any way?

**Comment by andryou** [comment]
@peterlaws take a look at #38 and see if that temporary workaround works for you. If it does, you'll be happy to hear that the next release eradicates that/this issue :)

**Comment by peterlaws** [comment]
Yep, seemed to fix it. Will monitor

**Comment by andryou** [comment]
@peterlaws v1.0.7.11 was just officially released which addresses this issue. Please confirm when you can and close this issue if resolved. Thanks!

**Comment by peterlaws** [comment]
It is now fine, but whatever you did broke the Chromecast Extension, the icon disappears from Youtube/Netflix/Twitch/etc players lol :/

**Comment by andryou** [comment]
Does anything appear in your blocked resources list when you have ScriptSafe enabled and the icon disappears?

**Comment by peterlaws** [comment]
Just the usual blocked stuff, nothing new

**Comment by andryou** [comment]
@peterlaws if you could, could you help test a potential fix?

Here are instructions:

1. Go to the Options page for your current ScriptSafe version
2. Copy everything in the Export box at the bottom of the page into a text editor
3. Keep the text editor open or save it to a text file
4. Download a ZIP of the latest code here: https://github.com/andryou/scriptsafe (click on **Clone or download** then **Download ZIP**)
5. Set up the beta version by skipping to step 2 in the second set of steps on: https://github.com/andryou/scriptsafe/wiki/Frequently-Asked-Questions#how-do-i-install-the-latest-version
6. Open the beta version's Options page, and copy/paste the contents you saved in step 2 into the Import box and click on Import

**Comment by peterlaws** [comment]
Maybe I'm doing it wrong or misunderstanding. I had to do step 2 in the FAQ?
> Extract the ZIP file to its own folder anywhere on your computer
Otherwise how do you manually install it via sep 5.

Either way, installed it (has new ID), and am seeing same behaviour re: Chromecast Icon disappeared.
What can I do next.

**Comment by andryou** [comment]
Thanks, and you temporarily disabled the web store version as well? 

Could you try disabling Block Click-Through Referrer and see if that helps? If not, try unticking <VIDEO>.

**Comment by peterlaws** [comment]
> Thanks, and you temporarily disabled the web store version as well?

I uninstalled it.

I tried disabling BCTR and <VIDEO> in turn and both disabled, same outcome.....

**Comment by andryou** [comment]
@peterlaws please repeat the steps in https://github.com/andryou/scriptsafe/issues/15#issuecomment-225772069 again, I believe the issue should be fixed (even with BCTR and <VIDEO> re-enabled). Please let me know, thank you!

**Comment by peterlaws** [comment]
Yep, it's back..

What was it JOOI? (nosey)..... I see you added a drop-down to BCTR.

**Comment by andryou** [comment]
ScriptSafe was also filtering "chrome-extension://" urls that were being injected by Google Cast (as well as LastPass), so I tightened down the scope to just urls that began with "http". And the BCTR drop-down is related to another ticket where it was breaking thumbnail enlarging in Tweetdeck (and I presume other sites as well).

**Comment by peterlaws** [comment]
I use LP and TweetDeck but I haven't seen any abnormalities.

Thanks a lot
