### ISSUE TITLE
Clean WebVR  

### ISSUE THREAD

**Issue by triceratops1** [andryou/scriptsafe#150]
WebVR: A technology [very simmilar] to webgl (but integrated with geolocation+device orientation apis)  

Could you add webVR  to the "whitenoisy" apis  at scriptsafe?

Source > https://blog.chromium.org/2016/12/introducing-webvr-api-in-chrome-for.html   

Thanks and Best regards

**Comment by andryou** [comment]
Thanks, the ability to block WebVR device enumeration will be added in v1.0.8.6:

![2017-01-12_17-53-13](https://cloud.githubusercontent.com/assets/4351175/21911729/0fa3477c-d8f0-11e6-9f7b-f7e02f8b87c9.png)

https://webvr.info/samples/00-hello-webvr.html

**Comment by andryou** [comment]
v1.0.9.0 Beta has been posted for testing :) #153

**Comment by triceratops1** [comment]
@andryou nice

**Comment by andryou** [comment]
v1.0.9.0 pushed to the Web Store, existing instances should auto-update shortly.
