### ISSUE TITLE
Font Fingerprinting

### ISSUE THREAD

**Issue by gameb0y** [andryou/scriptsafe#152]
Font fingerprinting – is what fonts you have, and how they are drawn. Based on measuring dimensions of the filled with text HTML elements, it is possible to build an identifier that can be used to track the same browser over time.

Font metric-based fingerprinting is tightly crossed with the canvas fingerprinting. It is probably weaker fingerprinting technique, since canvas gets not only bounding boxes but also pixel data. On the other hand font fingerprinting is much more difficult to defend.

https://browserleaks.com/fonts

Andry, can you block this?

**Comment by andryou** [comment]
Unfortunately I don't think it would be feasible or a good experience for users as this fingerprinting method uses very common JavaScript functions - http://www.lalit.org/lab/javascript-css-font-detect/

The main things it accesses to perform are  .style.fontFamily, .offsetWidth, and .offsetHeight, which are used almost everywhere and in most JavaScript frameworks as well.

The messy thing about this fingerprinting method is that it's not just limited to the above 3 items; they could also utilize .className and use CSS to set the font-family, then use .offsetWIdth and .offsetHeight to do the calculations.
