### ISSUE TITLE
v1.0.9.0 BETA - Help Test

### ISSUE THREAD

**Issue by andryou** [andryou/scriptsafe#153]
**What's changed from v1.0.8.5 to aid in beta testing:**

<ul>
							<li>Several improvements have been made to the ScriptSafe panel:
								<ul>
									<li>Changed to a one-column layout to better accommodate all languages and long domain names</li>
									<li>Fixed scrollbar issue where it would sometimes not scroll unless the bar itself was dragged</li>
									<li>Allows users to open several domains' ratings without having to reopen the panel each time</li>
									<li>Resolved issue with unscrollable long lists in other Chrome-based browsers</li>
									<li>Improved ability to access the Options, Refresh, Close buttons</li>
									<li>Domain control buttons are now all consistently displayed</li>
								</ul></li>
							<li>Added the ability to Block WebVR Enumeration (under Fingerprint Protection, option is disabled by default so feel free to enable it)</li>
							<li>Added ScriptSafe options to the right-click context menu (useful for popup windows with no controls)</li>
							<li>Fixed uncleared icon counter when there are blocked items for a tab and then ScriptSafe is disabled</li>
							<li>Improved Google Analytics (UTM) Tracking Removal to also strip out the utm_name parameter</li>
							<li>Updated unwanted content providers list</li>
							<li>Minor update to Swedish locale</li>
							<li>Minor code optimizations</li>
						</ul>

**Instructions on how to Beta Test:**
1. Download the v1.0.9.0 BETA: **https://github.com/andryou/scriptsafe/releases/download/v1.0.9.0_beta/ScriptSafe_v1.0.9.0_BETA.zip**
2. Extract the ZIP file to its own folder anywhere on your computer
3. Copy and paste **chrome://extensions** into your browser address bar and press Enter
4. Make sure you have disabled the Chrome Web Store version of ScriptSafe (ID: oiigbmnaadbkfbmpbfijlflahbdbdgdf)
   - Note: you may want to save a copy of your existing ScriptSafe settings at this point (see https://www.andryou.com/scriptsafe/frequently-asked-questions/#backup)
5. Enable “Developer Mode“
6. Click on **Load unpacked extension**, navigate to the folder you extracted ScriptSafe to in step #2 and click on OK
7. Restore your existing ScriptSafe settings: https://www.andryou.com/scriptsafe/frequently-asked-questions/#restore

**Any feedback/issues, please add it as a comment here or reply to my email I sent to all beta testers. If everything looks good, please let me know as well!**

Thank you!

**Comment by andryou** [comment]
A screencap of the new ScriptSafe panel (with an excellent use-case of the rationale behind the update):

![2017-01-13_13-00-02](https://cloud.githubusercontent.com/assets/4351175/21940040/699a4032-d990-11e6-96b2-072d33437547.png)

http://www.nationalpost.com/

**Comment by AdamF001** [comment]
Everything seems to be working just fine, good job! (Windows 10, Chrome 56 x64), the only thing noticed is that the mouse middle button for, Documentation, Options, and Github does not seem to be working.

**Comment by m32po** [comment]
#148 Domains' rating check works as I've always wanted, well done!

**Comment by andryou** [comment]
Updates:
* Added support for middle-mouse clicking to open panel links (e.g. Documentation, Options, Github)
* Improved panel button click behaviour (e.g. if xyz.com is the tab domain and it also has items listed under Blocked Items, then the two sets of buttons will sync when clicked)
* Added Spanish locale (reviewed and revised by Enrique Arróniz Ramos)
* Fixed potential issue where an allowed fingerprint option will prevent other allowed items from being listed

I hope to release v1.0.9.0 tomorrow (Wednesday); any issues in the scope of this beta are welcome (e.g. the changelog items). New feature requests and enhancements will be looked into after the public beta testing period is over.

**Comment by andryou** [comment]
v1.0.9.0 has been pushed to the Web Store! Thank you all for testing :)

I will start working on the ability to control the language, commits incoming.
