### ISSUE TITLE
Add option to block data: URLs

### ISSUE THREAD

**Issue by Monter** [andryou/scriptsafe#157]
Please add a option to block data: URLs, for example: data:text/html,BOOOM!
(see https://www.wordfence.com/blog/2017/01/gmail-phishing-data-uri/)

**Comment by andryou** [comment]
Thanks for this; very scary. I'll look into this after the beta testing period for v1.0.9.0 is over.

**Comment by andryou** [comment]
Coming in v1.0.9.1:

![2017-01-18_22-11-03](https://cloud.githubusercontent.com/assets/4351175/22092358/1fd93554-ddcb-11e6-9b04-388fe36531ae.png)

![2017-01-18_22-11-31](https://cloud.githubusercontent.com/assets/4351175/22092362/230e6ed8-ddcb-11e6-9909-2344481c7d29.png)

**Comment by andryou** [comment]
v1.0..9.1 Beta is now available for testing: #163

**Comment by andryou** [comment]
v1.0.9.1 has been published in the Chrome and Opera stores which addresses this issue. Thanks again for your report and testing!
