### ISSUE TITLE
Yahoo blocked as unwanted content

### ISSUE THREAD

**Issue by ROpdebee** [andryou/scriptsafe#16]
![screen shot 2016-06-02 at 16 06 28](https://cloud.githubusercontent.com/assets/15186467/15747650/0a64a004-28dc-11e6-9498-ef267c846dd5.png)

What's the reason for blocking the whole Yahoo domain? I can't visit legitimate pages (i.e. Yahoo! Answers) anymore.

**Comment by andryou** [comment]
Sorry about that, I created a script that optimizes the 4 HOSTS projects, using the root domain if too many entries (subdomains) exist for it. I just checked and there are 95 ad/tracking related servers on Yahoo. I will push out an update shortly which will fix this (but still block all 95 Yahoo ad servers), along with a couple of misc. tweaks. Thanks!

Very sorry about this.

**Comment by ROpdebee** [comment]
95?! Damn, then I don't blame you but I blame them... I managed to temporarily overcome this issue by just whitelisting answers.yahoo.com so it wasn't that big of a problem, just thought I'd notify you about the false positive. :)

**Comment by ROpdebee** [comment]
BTW, you could optimize the whole yoyo list further by using a binary search to determine if a domain is in the lists, as the array is sorted. I haven't looked through all the code but from what I can see, it's just doing a linear search, but do correct me if I'm wrong.

**Comment by andryou** [comment]
You are correct (the array is pre-sorted and it is currently doing a linear search); I've implemented binary search and I do notice an increase in performance. Will do some more testing and push out the update soonafter! Thank you for the suggestion.

**Comment by andryou** [comment]
![2016-06-02 14_06_52](https://cloud.githubusercontent.com/assets/4351175/15755604/88dc012c-28cb-11e6-8f8e-18e6a8017136.png)

The changelog for v1.0.7.4 (coming shortly) will mention **"noticeable performance increase"**, here are some numbers (consistent in my testing) :)

**Comment by ROpdebee** [comment]
That's a nice improvement!

**Comment by andryou** [comment]
Pushed v1.0.7.4, please test if yahoo.com is still blocked and close this ticket if is isn't :)
Thanks for all your help.

**Comment by ROpdebee** [comment]
Yahoo's fixed, thanks!
