### ISSUE TITLE
Manually add entries for fingerprint protection

### ISSUE THREAD

**Issue by rEnr3n** [andryou/scriptsafe#161]
ScriptSafe v1.0.9.0

I have "prevent clipboard interference" checked. When I go to youtube I get a different context menu on the video. The same happens for embedded videos. I don't get the clipboard interference in the blocked items so I am unable to unblock it. It would be great if you add an option to add sites manually just like in the white/blacklist settings.

**Comment by andryou** [comment]
Thanks, will be added in the next release!

**Comment by andryou** [comment]
v1.0..9.1 Beta is now available for testing: #163

**Comment by andryou** [comment]
v1.0.9.1 has been published in the Chrome and Opera stores which addresses this issue. Thanks again for your report and testing!
