### ISSUE TITLE
ability to disable toggle menu

### ISSUE THREAD

**Issue by tripscripts** [andryou/scriptsafe#162]
some users may not want the toggle (right click) menu, can you please add an option for us to disable it?

THANKS

**Comment by andryou** [comment]
Thanks, will be coming in the next version!

**Comment by andryou** [comment]
v1.0..9.1 Beta is now available for testing: #163

**Comment by tripscripts** [comment]
loaded it up, and it works perfectly

thanks for all your hard work!
