### ISSUE TITLE
Bad UI behavior

### ISSUE THREAD

**Issue by Soncomander** [andryou/scriptsafe#163]
I didn't find a pattern, but on some sites the UI panel is "broken".

- The main page buttons don't exists.
- The secondary pages buttons don't interact (nothing happens when clicked).

If you left-click and use Clear/Temporary/Allow the UI panel works normally.

![bug](https://cloud.githubusercontent.com/assets/11232768/22174594/4f67358c-dfc9-11e6-80fa-75e18974b935.png)

Using Xubuntu 16.10 - Chromium

**Thanks!!**

**Comment by Razinal** [comment]
me too.
Win 10 x64 Pro, Chrome 55 64-bit.

the only things visible in the UI are c.amazon-adsystem.com  and NOSCRIPT in any *.wordpress.com .

**Comment by andryou** [comment]
Thank you; I've reproduced this and have committed a fix. This will be included in the next release; will start public beta testing soon to get a release out as soon as possible.

**Comment by andryou** [comment]
v1.0..9.1 Beta is now available for testing: #163

**Comment by andryou** [comment]
v1.0.9.1 has been published in the Chrome and Opera stores which addresses this issue. Thanks again for your report and testing!
