### ISSUE TITLE
Blocking webbugs removes pictures

### ISSUE THREAD

**Issue by IDKwhattoputhere** [andryou/scriptsafe#164]
The images are blocked as WEBBUGs:
`https://blog.disqus.com/unlock-content-engagement-insights-in-the-new-disqus-analytics`

![](https://cloud.githubusercontent.com/assets/16030872/22179067/0610cfe4-e049-11e6-99e4-239ed78e82b5.png)
Can't tell if this is a bug or if it's the way the images are embedded.

ScriptSafe v1.0.8.5
Chrome 55.0.2883.87

**Comment by andryou** [comment]
Thanks, I checked and blog.disqus.com is included in hpHOST's blocklist as an ad/tracking server since December, 3, 2014: https://hosts-file.net/default.asp?s=blog.disqus.com

Please let me know your thoughts, such as if this is a limited use case limited to only a couple of sites.

**Comment by IDKwhattoputhere** [comment]
I didn't know this feature used blocklists. I never had an issue with it before.
I noticed the domain was listed in hpHosts because of uBlock Origin blocking it too so I reported it on `forum.hosts-file.net`.

Thanks for the answer, your work and feel free to close the issue.

**Comment by andryou** [comment]
Thank you for your kind words and for the update!

**Comment by andryou** [comment]
I see it has been removed from hpHosts, so I will ensure I use the latest update in v1.0.9.1.
