### ISSUE TITLE
v1.0.9.1 BETA - Available for Testing

### ISSUE THREAD

**Issue by andryou** [andryou/scriptsafe#166]
**What's changed from v1.0.9.0 to aid in beta testing:**

<ul>
							<li>Added option to block Data URLs (data:text/html) to protect users against <a href="https://www.wordfence.com/blog/2017/01/gmail-phishing-data-uri/" target="_blank">new phishing attacks</a> (disabled by default) - #157 - <a href="https://www.andryou.com/dataurltest.html" target="_blank">test page</a></li>
							<li>Added the ability to set ScriptSafe's interface language (found at the top of the Options page) - #145 </li>
							<li>Improved ScriptSafe panel scalability in terms of font size and screen resolution - #17 </li>
							<li>Added option to show or hide the ScriptSafe context (right-click) menu - #162 </li>
							<li>Fixed occasional panel loading issue when NOSCRIPT blocking is enabled - #159 + #163 </li>
							<li>Added ability to manually add domains to fingerprint whitelists - #161 </li>
							<li>Minor update to the Chinese - Simplified translation</li>
							<li>Updated unwanted content providers list</li>
							<li>Minor optimizations</li>
						</ul>

**Instructions on how to Beta Test:**
1. Download the v1.0.9.1 BETA: **https://github.com/andryou/scriptsafe/releases/download/v1.0.9.1_beta/ScriptSafe_v1.0.9.1_BETA.zip**
2. Extract the ZIP file to its own folder anywhere on your computer
3. Copy and paste **chrome://extensions** into your browser address bar and press Enter
4. Make sure you have disabled the Chrome Web Store version of ScriptSafe (ID: oiigbmnaadbkfbmpbfijlflahbdbdgdf)
   - Note: you may want to save a copy of your existing ScriptSafe settings at this point (see https://www.andryou.com/scriptsafe/frequently-asked-questions/#backup)
5. Enable “Developer Mode“
6. Click on **Load unpacked extension**, navigate to the folder you extracted ScriptSafe to in step #2 and click on OK
7. Restore your existing ScriptSafe settings: https://www.andryou.com/scriptsafe/frequently-asked-questions/#restore

**I hope to publish v1.0.9.1 before the end of this week, so I'd appreciate it if you can give this beta a quick drive whenever you get the chance :)**

Any feedback/issues, please add it as a comment here or reply to my email I sent to all beta testers. **If everything looks good, please let me know as well!**

Thank you!

**Comment by cewood** [comment]
Just installed this released, and VERY pleased to report that it finally works with Google Music and the context menus used for creating/updating/deleting playlists, etc. Thanks for working to resolve these and other issues related to hidden/incorrectly blocked resources, etc.

That has been a major bug preventing me from using this plugin full time. I've just re-enabled the plugin and I'll report back if I uncover any issues.

**Comment by AdamF001** [comment]
Everything seems to be fine, the only thing noticed is when creating the popup "data:text/html,<script>alert('hi');</script>" it still creates the popup and does not block it, in the menu 
![failedtoblock](https://cloud.githubusercontent.com/assets/24633575/22227499/7b9ea5b2-e1c3-11e6-8680-daec629530ed.png)
![panel](https://cloud.githubusercontent.com/assets/24633575/22227520/96559b36-e1c3-11e6-879a-324b18f42c2f.png)
After distrusting it still shows the popup.
![panel](https://cloud.githubusercontent.com/assets/24633575/22227550/c9cc72be-e1c3-11e6-9837-a5bc2a9bb20a.png)
but everything else is fine,love the new one row style :D (Windows 10 x64, Chrome 56 x64)

**Comment by andryou** [comment]
@AdamF001 the Data URLs blocking only applies to A elements that explicitly link to a data:text/html URI. Unfortunately the Chrome API does not give me access to detect data:text/html URIs directly, so I had to make do with what I did have access to. The good thing is that most phishing attempts are done through A elements (e.g. via email messages), like on the demo page I put together: https://www.andryou.com/dataurltest.html

I hope this clarifies things!

**Comment by AdamF001** [comment]
Great, I thought the extension had full control, sadly as I can see it does not :/ but that's alright, everything else seems to work perfectly.

**Comment by andryou** [comment]
Minor updates (on Github - not in the posted beta - but will be included in the published stable):
* "Show in Context Menu" string translated into Korean and Dutch
* "Trust / Distrust" strings in the Options page now dynamically update when language is changed
* Panel updated to not show any options for data:text/html URIs

And good news, just an hour or so ago ScriptSafe was approved and included in the Opera Store! (https://addons.opera.com/en/search/?query=scriptsafe) It is currently an older version (v1.0.8.5), but I plan to submit v1.0.9.1 to the Opera Store at the same time I submit it to the Chrome Web Store.

**Comment by gameb0y** [comment]
if Block Client Rectangles enabled, twitter not working properly
![untitled](https://cloud.githubusercontent.com/assets/19530450/22298396/4977b37a-e318-11e6-9702-0427b22afe47.jpg)

**Comment by andryou** [comment]
Thanks @gameb0y; you will have to allow/temporarily allow Client Rectangles for twitter.com:

![2017-01-25_11-09-48](https://cloud.githubusercontent.com/assets/4351175/22298549/df82f4f8-e2ee-11e6-9a51-882f66ae9f90.png)

**Comment by andryou** [comment]
Just a note - I hope to release v1.0.9.1 tomorrow (Thursday), so I welcome any comments/updates: whether or not this beta is working well :)

**Comment by AdamF001** [comment]
v1.0.9.1 is working correctly according to tests on Windows 7 x64 Chrome 56 x64 and Windows 10 x64 Chrome 56 x64. Everything is great no random UI blackouts, no errors encountered with Data:urls. just great. waiting for the official release ^^, and congrats for reaching the Opera webstore!

**Comment by andryou** [comment]
Thank you all! v1.0.9.1 has been pushed to the Chrome Web Store, as well as Opera Add-ons :)
