### ISSUE TITLE
Unable to unblock

### ISSUE THREAD

**Issue by ortreum** [andryou/scriptsafe#167]
Hello,

On
http://fontawesome.io/get-started/#modal-download
the "blocked" list is empty. So the download button does not work.

![blockedlist](https://cloud.githubusercontent.com/assets/2929515/22285096/8731d854-e2ea-11e6-939a-c6e3bbb124a1.jpg)

Best regards,
Michael

**Comment by andryou** [comment]
Thanks for the report! I'm happy to say this was reported (#159 + #163) and
has been addressed in the v1.0.9.1 beta. You can find the beta version
here: #166

Feel free to test it to ensure it addresses this issue :)

**Comment by andryou** [comment]
v1.0.9.1 has been published in the Chrome and Opera stores which addresses this issue.
