### ISSUE TITLE
Twitter Not Working

### ISSUE THREAD

**Issue by mpgchgo** [andryou/scriptsafe#170]
Hi Andrew! Love ScriptSafe! But lately I cannot connect to Twitter. I see a number of pop-up windows that can't be clicked away. At best I can dismiss them, but am left with a greyed-out screen. There are only two possible fixes - disable ScriptSafe entirely, or block scripts from abs.twimg.com. The latter, of course, renders the site unusable. I can't even log in! 

Using Chrome 55.0.2883.95 (64-bit) on MacOS Yosemite 10.10.5

**Comment by andryou** [comment]
Hi! Please click on "Client Rectangles" in the panel and click on Allow :)

**Comment by mpgchgo** [comment]
That fixed it! Thanks! I didn't even notice the "Client Rectangles" option. :) Sheesh! :+1:
