### ISSUE TITLE
Feature Idea: Ability to block <div> elements separately?

### ISSUE THREAD

**Issue by AdamF001** [andryou/scriptsafe#173]
Adding the ability of blocking <div> elements where advertisements can be displayed? Just an idea, Thanks for considering ^^ (Maybe with a right click block <div> element context?)

**Comment by andryou** [comment]
This is unfortunately not in the scope of ScriptSafe; this is moreso in the realm of an adblocker like uBlock Origin (which I highly recommend over other adblockers).

I appreciate your idea though!
