### ISSUE TITLE
ScriptSafe for Firefox. Yes, I've seen the not at this time replies, read please.

### ISSUE THREAD

**Issue by B3bomber** [andryou/scriptsafe#179]
Noscript does not have as many options as this does and is also developing an issue the more it is updated when it comes to subdomains of the main site that is set to allow scripts. It will generally NOT apply or even show the subdomains those sites have (but does show the other crap not part of the stuff I need to enable scripts for, it's a pain in the ass).

Short version, I have put the URL I cannot load properly into my browser that uses ScriptSafe to get the URL of the subdomain then copy/paste that URL into Noscript's whitelist to get the damn site to work.

I'm not sure your canvas blocker works. https://panopticlick.eff.org/
ScriptSafe happily blocks the entire site from running. To run the test I have to allow the site and from there on apparently all canvas protections do nothing. Not even the DISABLE CANVAS in chromium itself option. Noscript will run that site without me whitelisting stuff (something about .js handling and being properly swapped to the non .js links for testing). As for the results, it is able to identify what browser I even use (I have a user agent spoofer on both browsers, of which only the Firefox one seems to work).

So ScriptSafe fails the fingerprint test entirely. User agent spoofer should make it show up as FireFox (it doesn't work either and that isn't your extension but it is odd both of them fail).

Edited a typo and one wrongly added word.

**Comment by andryou** [comment]
I'm happy to say that with Firefox's move to Web Extensions, I've ported ScriptSafe over and approved around 30 minutes ago! https://addons.mozilla.org/firefox/addon/script-safe/
