### ISSUE TITLE
ScriptSafe Conflict with HTTPS Everywhere

### ISSUE THREAD

**Issue by perknh** [andryou/scriptsafe#187]
Hello andryou,

I'm getting the warning I have copied below quite frequently.  In this case, HTTPS Everywhere is doing the right thing.  As for my computer's configuration, I'm running both Chromium (55.0.2883.87) and Chrome-beta (57.0.2987.74 beta) within 64-bit Peppermint Linux OS (Peppermint 7 Respin) --which is based off of Ubuntu 16.04.1. The current kernel is 4.8.0-39-generic x86_64.  My laptop computer is a Satellite C70-A.

Thanks so much,

perknh

Warning:
This extension failed to redirect a network request to http://connect.facebook.net/en_US/sdk.js because another extension (HTTPS Everywhere) redirected it to https://connect.facebook.net/en_US/sdk.js#xfbml=1&amp;version=v2.4.

**Comment by andryou** [comment]
Hi perknh, you can safely disregard the message, it's benign and is caused by two or more extensions modifying the same request (in this case connect.facebook.net) at the same time.

**Comment by perknh** [comment]
>
> Hi perknh, you can safely disregard the message, it's benign and is caused
> by two or more extensions modifying the same request (in this case
> connect.facebook.net) at the same time.


​Will do.  Thank you, Andrew.  Yes, so far, that's the only time I've ever
seen that message, but it's everywhere!!!!

perknh​
