### ISSUE TITLE
Scriptsafe not Google friendly

### ISSUE THREAD

**Issue by Sulhir** [andryou/scriptsafe#2]
When enabled in Chrome attempting to search from the address bar will work briefly.  Eventually when searching from the address bar nothing will happen at all.  For example - when searching for the term "search" this web address <https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8> will pop up but only a blank white web page with absolutely nothing it appears.  Sometimes reloading the page can make the Google search page pop up but the text that should have been searched will no longer be present and no results displayed.  Only disabling the extension entirely when searching resolves the issue completely.  The issue is intermittent but definitely connected to ScriptSafe.

**Comment by andryou** [comment]
Thanks! Can you please let me know if this issue is still occurring in v1.0.6.19?

**Comment by rancyd** [comment]
This is fixed on my windows 10 machine after 1.0.6.19

**Comment by andryou** [comment]
Good to hear, thanks for the update!

**Comment by andryou** [comment]
Whoops sorry, will re-open and wait for Sulhir to reply

**Comment by Sulhir** [comment]
Don't worry, I'll be sure to bug you if have any further problems
