### ISSUE TITLE
Please stop with the updates

### ISSUE THREAD

**Issue by stupid-genius** [andryou/scriptsafe#20]
Please put together a coherent release and then push it all at once--my computer is not your personal sandbox.  Your extension is about to get uninstalled.

**Comment by andryou** [comment]
Noted, thank you

**Comment by andryou** [comment]
Will limit pushing updates to the Chrome Web Store to at most 1 in a day (if needed). I've gotten feedback from other users relating to this. My apologies to all.

**Comment by stupid-genius** [comment]
Well, I appreciate that you're willing to respond to feedback, but once a day is still too much.  Maybe once a month.  Or give me some kind of control over when I apply updates.  This is my development machine and I can't tolerate daily changes that could potentially disrupt my work.

**Comment by stupid-genius** [comment]
Perhaps have a canary version for those that want bleeding edge builds and a stable version that only gets the aggregated updates more infrequently.  You could hide it in the store if you don't want to encourage people that don't know any better to use that one.

**Comment by andryou** [comment]
Recent versions of ScriptSafe have a listener for when a new update is available (and shows the notification). It does not actually install the update; it only does so when you restart your browser.
Before this, it used to go ahead and install the update without any notification or waiting for you to restart your browser (which would disrupt the browsing session).

The next version will include an option to hide the update notification message.

**Comment by stupid-genius** [comment]
The message is not the problem.  The update is the problem.  If you continue updating the code on my machine with such regularity (daily, or even weekly, is unacceptable), I'm going to be forced to remove the extension.  Which will suck because I really like it.  But my computer is how I make my living and I will not have you pushing this many code updates as if my machine were your personal sandbox environment.

Your tag line is "A Chrome extension that gives users control..." -- ok, give me control.

**Comment by andryou** [comment]
I understand where you're coming from and I certainly don't want to lose one of my users!

If you like a particular version (https://github.com/andryou/scriptsafe/releases) you can download it and load it as an unpacked extension. Or alternatively sync it with Github, so you can sync whenever you want the latest release.

In the manifest you may want to remove this entire line just to be safe: **"update_url": "http://clients2.google.com/service/update2/crx",**

Just a heads up: I'm doing testing right now and will push out a release today on the webstore which will notably fix syncing (quite an important issue) and will introduce hotkey support.

**Comment by stupid-genius** [comment]
As I said, I'd edited the manifest, but updates were still coming down.  I even deleted the update after it downloaded, but then some hook triggered the next time I started the browser and deleted the existing version (probably expecting to have the new one) and I had to re-install.  I suspect it's your listener that's still updating the extension.  I had previously started down the path of loading it locally, but I suspect that it would still update all the same.  Where about is that listener you mentioned?  I'll try removing that locally.

**Comment by andryou** [comment]
Very strange. And you're loading it as an unpacked extension (in a new folder outside of the default Chrome extensions folder)?

The listener is here: https://github.com/andryou/scriptsafe/blob/master/js/scriptsafe.js#L618
And the manifest line (you're aware of this, but just wanted to point it out) is here: https://github.com/andryou/scriptsafe/blob/master/manifest.json#L49

**Comment by stupid-genius** [comment]
Ok, well, you apparently decided to ignore the feedback about constant changes and continue to push updates almost daily.  And now you've introduced a bug that's breaking pages ("Aww, Snap!").  I know it is caused by your extension because it's 100% reproducible and I don't get the error when I disable your extension.  This is precisely the problem with constant updates--this extension has worked fine for *so long*, but now that, for some reason, you've decided you must be constantly updating, it's become unreliable.  I didn't install this extension because I needed something to troubleshoot in my spare time.  The public's computers are not your personal sandbox.  And now it must come out of all my browsers.

**Comment by stupid-genius** [comment]
The problem with pulling a tagged release and side-loading is that there's no easy update mechanism.  I don't want **no** updates.  I want **infrequent** updates.  Updates that have had some time to be tested and stabilize.  You seriously need to release a second, "canary" version of the app in the store and have that one be built off of HEAD.  Only once it's been stable for a while should you do a tagged release to the mainline extension.  I'm not your QA.
