### ISSUE TITLE
Compatibility problems with uBlock Origin

### ISSUE THREAD

**Issue by hippostar** [andryou/scriptsafe#218]
Chrome often has a yellow exclamation mark showing "Extensions Errors". When you click on it, this error is listed in the extensions page underneath scriptsafe. Maybe this should just not be a warning shown to the end user? 

Warning:
This extension failed to redirect a network request to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACklEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg== because another extension (uBlock Origin) redirected it to data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==.

**Comment by AykutCevik** [comment]
Have a look at #186 and #80 and other issues, this has already been addressed. Unfortunately you can't disable this warning :/
