### ISSUE TITLE
Scriptsafe is now always un-enabled when starting Chrome...

### ISSUE THREAD

**Issue by BubbaHoTep3489** [andryou/scriptsafe#22]
Does anyone know why Scriptsafe is now un-enabled every time Chrome is started? It used to always be enabled when Chrome was started. Is it some new safety feature? Thanks!

**Comment by andryou** [comment]
There's a lengthy discussion in #6, but you may need to manually re-enable it by going to Chrome settings, Extensions, and ticking "Enabled". You may be asked to accept new permissions (the new one being "Privacy").

**Comment by BubbaHoTep3489** [comment]
Whoa, that was fast! Yes, I've been re-enabling it every time. I'll read that #6.

**Comment by andryou** [comment]
If it's still persistent, you may need to do a clean install of ScriptSafe (just make sure you save everything under the "Export" box in the ScriptSafe options page to re-import back)

**Comment by BubbaHoTep3489** [comment]
I read that #6...sorry, but  being a user, and not a coder, all that just flew right over my head. If the issue still persists after a few more days, I'll try a clean install. Thanks for your swift responses!

**Comment by andryou** [comment]
No worries! Sounds good, ensure you have a backup of your settings before you remove ScriptSafe and re-install it again, so that you're back up and running in no time (the note in my previous reply).

**Comment by BubbaHoTep3489** [comment]
Hi,How does the 'save export' box work? I've clicked the Export 'select all', then 'Save', but nothing happens. No confirmation that anything was saved, or where it was saved to. Can I just highlight the contents of the box copy/paste it into a word doc,then do a clean install, then copy back from the word doc into the import box?
Thanks!

**Comment by andryou** [comment]
> Can I just highlight the contents of the box copy/paste it into a word doc,then do a clean install, then copy back from the word doc into the import box?

Yup! Except I'd recommend pasting it into Notepad instead of Word (because Word sometimes auto-formats text).

**Comment by BubbaHoTep3489** [comment]
HI,Sorry to bother you again....
I've 'clean-installed' the newest version of Sciptsafe,but I can't seem to block the following(that I used tobe able to block):
comet.yahoo.comdata.mail.yahoo.compc.comet.yahoo.comprod.iris.yahoo.comucs.query.yahoo.com
On each one, I've tried 'Deny', 'Distrust', they all came backas 'Allowed Resources'.
Then I tried adding all of them to the Blacklist, and saving.They all came back.
Either something has changed with this new version, or I'm doing somethingwrong(probably).
I've also closed down Chrome and restarted it, and also re-booted my PC, and re-started Chrome, those Resources are still there.
Any ideas of how to block them?
Do you take PayPal donations? I'm retired, and can't afford much, but I'd liketo donate something for all your help(and your great product)!
Thanks!

**Comment by andryou** [comment]
No worries! I can't seem to reproduce it; do you have "Preserve Save-Domain" enabled? (if so, this would be expected behaviour when visiting a Yahoo domain) And can you take a look through your whitelist to make sure there is no yahoo.com entry? (especially no *.yahoo.com entry)

About the donation, don't worry about it! Just knowing you're enjoying ScriptSafe makes me happy :)

**Comment by BubbaHoTep3489** [comment]
HI,No, 'Preserve Save-Domain' in not checked, and there's no yahoo.com in my white list.
I did notice a new update today, that added new 'unwanted' buttons. 
When I clicked them, all those yahoo.com resources that I mentioned last time moved up to the 'Blocked Resources' section.

**Comment by andryou** [comment]
Can you provide me a URL that I can try to reproduce this on? Thanks!

**Comment by BubbaHoTep3489** [comment]
I think I got lost somewhere along the line....what are you trying to reproduce? Everything is back to working like it used to. I was working with yahoo.com and it's email.

**Comment by andryou** [comment]
Oh that's good to hear! I thought you were still experiencing issues.
