### ISSUE TITLE
Hotkeys missing

### ISSUE THREAD

**Issue by intre4si32** [andryou/scriptsafe#240]
I try to configure hotkeys but clicking on the button just opens the extensions page. there I open the options once again to have a look at the hotkeys button. It's like a loop.
Is there something broken or not supposed to even be there?
On chrome latest 60.0.xxxxx windows 10 x64

**Comment by solenwin2** [comment]
Issue

**Comment by SHHSSH** [comment]
I have this problem too, running a linux distro with Chrome. Anychance we could have this embedded into the options please?

**Comment by solenwin2** [comment]
Readme_edit.

**Comment by intre4si32** [comment]
OK found them they are on the chrome://extensions page down at the bottom. it's like a global page for the hotkeys. No issue with it anymore.
