### ISSUE TITLE
Bug report: interference between extensions

### ISSUE THREAD

**Issue by urfausto** [andryou/scriptsafe#242]
Hi, on my browser i have enabled both **scriptsafe** and **ublock origin** and i have been noticing the underlying bug in the extension page of the browser, i have however no problems in the browsing but i want to ask if there is a way to fix this.
my specs: windows 7 64bit, vivaldi browser 64bit

Questa estensione non è riuscita a reindirizzare una richiesta di rete a data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw== perché un'altra estensione (ScriptSafe) l'ha reindirizzata a data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACklEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg==.

**Comment by AykutCevik** [comment]
Already known, please have a look at #218 and the other linked issues in the post.
You can safely disregard the message.

**Comment by urfausto** [comment]
thanks man, i didn't know and i was receiving multiple warnings like that from few extensions.

i put this here for everybody: https://github.com/gorhill/uBlock/issues/1170#issuecomment-168989068
