### ISSUE TITLE
Webextension for Firefox.

### ISSUE THREAD

**Issue by gegemon2012** [andryou/scriptsafe#243]
Hello!
I really liked your extension. I tried it on Google Chrome and realized that it is much more convenient and faster than NoScript on Firefox and there are more security settings in it. Also, the interface is not overloaded. Soon Firefox will switch to support for webextension and NoScript on it will not work, if it's remade, it's not known what will happen in the end. So now I see the point of adapting your plug-in on Firefox. I would love to switch to Chrome, but its mobile version does not support plugins and it does not block ads ...

**Comment by bollerdominik** [comment]
The all new Firefox Quantum version does not allow an NoScript installation. AFAIK there is no alternative that works on the new Firefox engine.
I would love ScriptSafe to be the new replacement for NoScript on Firefox!

**Comment by andryou** [comment]
I will look into this after ScriptSafe v1.0.9.2 is released! (currently in beta: #279)

**Comment by andryou** [comment]
Well, that was easier than I expected.

![2017-12-01_1-14-14](https://user-images.githubusercontent.com/4351175/33470214-124879a0-d635-11e7-9c65-77610a03331b.png)

**Comment by andryou** [comment]
I ended up not sleeping. Enjoy! https://addons.mozilla.org/firefox/addon/script-safe/
