### ISSUE TITLE
Respect Same-Domain issues

### ISSUE THREAD

**Issue by mprangenberg** [andryou/scriptsafe#25]
As per the latest changelog: "Made "Respect Same-Domain" behaviour more secure; now requires you to allow/temporarily allow a blocked page in order for it to load same-domain elements"
This, for me, is unwanted behavior. For example: I want to browse facebook. I have to (temporarily) allow facebook to do that. The problem is now, i just want to allow it in its own tab, but this enables it in all other tabs and pages as well, doesn't it? 
From the top of my mind there are 2 ways this could be tackled:
1. Add a "Respect Same-Domain" button to the popup, which would whitelist pages just for this feature.
2. Add a relaxed mode for this, which behaves like previous versions.

**Comment by andryou** [comment]
Thanks, your explanation makes sense. I will revert my change regarding this behaviour in the next update.

**Comment by andryou** [comment]
Reverted in v1.0.7.8.

**Comment by andryou** [comment]
(@mprangenberg  sorry for the delay in getting v1.0.7.8 to you; I checked and it's still "Pending Review" in the Chrome Web Store)

**Comment by andryou** [comment]
Re-opening until v1.0.7.8 is approved by Chrome/Google. It's been "Pending Review" for about 12 hours.

**Comment by chrcoluk** [comment]
still waiting :( having to set lots of sites to temp :( but dont want to disable the extension as I also dont want to give scripts a free for all.

**Comment by chrcoluk** [comment]
ok I realised how to load 1.7.8 manually, so to help others do this process.
First export settings from webstore version, as is stored in different path.
Disable webstore version.
Unpack src code somewhere.
In extensions load the extracted src code from directory.
Then import settings on the manual installed version and make sure enabled.

I guess when webstore gets the update, then disable the manual version and reenable webstore version else wont get automatic updates.

hope this helps.

**Comment by andryou** [comment]
And just to add to the above, you can download v1.0.7.8 here: **https://github.com/andryou/scriptsafe/releases/tag/v1.0.7.8**

**Comment by andryou** [comment]
I've been refreshing the Developer Dashboard all day to check on the status and I'm happy to announce v1.0.7.8 has been published on the Chrome Web Store within the past half hour.

**Comment by at0micboy** [comment]
Its works! Thanks a lot :)

**Comment by chrcoluk** [comment]
yep noticed, thanks.

Unloaded the manual install now :)

**Comment by andryou** [comment]
Good to hear, thank you all for your patience!

**Comment by Aybee** [comment]
Thank you for 1.0.7.8 now it seems to work again.

But the new tab looks strange to me (not with 1.0.7.6). My theme is not visible on a new tab and I can see no google images on this tab and maybe more. 

Here is my config, maybe I'm missing something
```
annoyances         | true
annoyancesmode     | relaxed
antisocial         | true
applet             | true
audio              | true
blackList          | []
classicoptions     | false
cookies            | true
domainsort         | false
embed              | true
enable             | true
frame              | true
iframe             | true
image              | true
lastSync           | 1430097323047
linktarget         | off
mode               | block
noscript           | true
object             | true
preservesamedomain | true
rating             | false
referrer           | true
referrerspoof      | off
refresh            | true
script             | true
sync               | true
syncenable         | false
syncfromnotify     | true
syncnotify         | true
tempregexflag      | true
updatemessagenotify| true
updatenotify       | true
useragentspoof     | off
useragentspoof_os  | off
video              | true
webbugs            | true
webrtc             | default_public_interface_only
whiteList          | [
                      "translate.googleapis.com",
                      "talkgadget.google.com",
                      "mail.google.com",
                      "*.youtube.com",
                      "s.ytimg.com",
                      "maps.gstatic.com"
                    ]
xml                | true
```

**Comment by andryou** [comment]
@Aybee thanks, it will be addressed in the next update, which I will release within the week

**Comment by Aybee** [comment]
Thank you. Here is a screenshot. Strange that it says "no external resources" as I think if I add `google.de` to the whitelist everything might be fine. (This is with empty white and blacklist)

![scriptsafe1 0 7 8](https://cloud.githubusercontent.com/assets/1143013/15877699/c336775a-2d15-11e6-86a6-1db1ac407c6f.png)

This is with `google.de` on whitelist

![scriptsafe1 0 7 8-2](https://cloud.githubusercontent.com/assets/1143013/15877712/d8936b94-2d15-11e6-841c-90fb1bb9020c.png)

And a big thank you for this extension as I think this is the best one to stop external resources. **Same origin** is that what I always was looking for. I use ScriptSafe for a long time now.

**Comment by andryou** [comment]
@mprangenberg thanks! I was able to reproduce it and I've fixed it in [this commit](https://github.com/andryou/scriptsafe/commit/2982f9e12b7e912e287ec3b8b2d7bdc3714fbe72).

Re: my announcement in #29, I will wait a bit to fix any more reported issues and also thoroughly test ScriptSafe before pushing an official update out onto the Chrome Web Store, so please hang in there :) Whitelisting google.de is a good workaround in the meantime (in my research, the new tab loads chrome://newtab, which loads a page hosted on google.[region], in your case [region] is **de**).

**Comment by Aybee** [comment]
> @andryou Whitelisting google.de is a good workaround in the meantime ...

Yes, but resources should be visible in the dropdown.

BTW I think it does not matter how often an update gets published. When your work is done you should publish it. It also shows that the developer is working hard on it.  :smiley:

**Comment by andryou** [comment]
Some good news, managed to get it to recognize the new tab page and resources :)

![2016-06-07_23-47-04](https://cloud.githubusercontent.com/assets/4351175/15882188/372e89ec-2d0a-11e6-9c95-3ac03ca3918a.png)
