### ISSUE TITLE
Trustwave blog graphics fail under ScriptSafe

### ISSUE THREAD

**Issue by Papoulka** [andryou/scriptsafe#258]
https://www.trustwave.com/Resources/SpiderLabs-Blog/The-Spam,-JavaScript-and-Ransomware-Triangle/?page=1&year=0&month=0&LangType=1033

All tables and graphic elements on this page stay blank until I completely disable ScriptSafe.  "Allow all blocked for session" doesn't help.

**Comment by hlein** [comment]
Hm.  Same here, ScriptSafe's drop-down indicates nothing blocked but <WEBBUG>.

This looks similar to #262

View source on the blog post, and you'll see various links to aN.typepad.com URLs.  Open one of those links and you'll finally see ScriptSafe is blocking them; allow them and then refresh the Trustwave blog, and now those tables & figures start rendering.  Why you need JS just to display some canned images...

**Comment by andryou** [comment]
Beta has been released: #279

**Comment by andryou** [comment]
Now available in v1.0.9.2 which has been officially released.
