### ISSUE TITLE
Embedded Typepad images falsely blocked as webbugs

### ISSUE THREAD

**Issue by matthew-cline** [andryou/scriptsafe#262]
Go to [this Typepad post](http://lizditz.typepad.com/i_speak_of_dreams/2013/02/the-facebook-flounce-with-diagrams-and-pictures.html) with general settings change to enable `<IMG>`.  The page has multiple embedded images with URLs that look like [http://lizditz.typepad.com/.a/6a00d83451b6fc69e2017ee8a1f3d1970d-450wi](http://lizditz.typepad.com/.a/6a00d83451b6fc69e2017ee8a1f3d1970d-450wi).  These images get blocked as webbugs unless `*.typepad.com` is whitelisted.

**Comment by andryou** [comment]
Thanks, www.typepad.com is included in https://hosts-file.net/ad_servers.txt, which my optmizing script interprets as *.typepad.com. I'll create an exclusion for this domain. This will also address #258

**Comment by andryou** [comment]
Beta has been released: #279

**Comment by andryou** [comment]
Now available in v1.0.9.2 which has been officially released.
