### ISSUE TITLE
userstyles.org - Blank Pages

### ISSUE THREAD

**Issue by war59312** [andryou/scriptsafe#263]
Hi,

userstyles.org pages display blank with ScriptSafe enabled. Have to display completely or pages won't load.

Example page @ https://userstyles.org/users/3165

Hit F12 in chrome to see all the errors that get logged while ScriptSafe is enabled. No such errors with ScriptSafe disabled.

Thanks,

Will

**Comment by andryou** [comment]
If you allow userstyles.org, the page loads properly.

**Comment by war59312** [comment]
userstyles.org is already allowed. :(

**Comment by war59312** [comment]
Still broken with ScriptSafe v1.0.9.3

@andryou Mind taking another look please?
