### ISSUE TITLE
Log available?

### ISSUE THREAD

**Issue by 1stone** [andryou/scriptsafe#273]
I've trouble with loading a particular website with ScriptSafe enabled.
Although the site has been whitelisted, some particular element is obviously blocked by ScriptSafe (observed by a very short flickering of the plugin icon), causing an endless redirection loop on the site.
With ScriptSafe disabled, the site loads fine.

I would like to find out which particular request is causing this problem, but I'm unable to find any log (e.g. of blocked requests) that would allow me to identify the problem.
The options of the ScriptSafe plugin dialog don't show any log capability.

If this is not available in ScriptSafe, is there another way to achieve this?

**Comment by andryou** [comment]
Coming soon! https://twitter.com/andryou/status/935381819654070272

**Comment by andryou** [comment]
Beta has been released: #279

**Comment by andryou** [comment]
Now available in v1.0.9.2 which has been officially released.
