### ISSUE TITLE
v1.0.9.2 BETA - Ready for Testing

### ISSUE THREAD

**Issue by andryou** [andryou/scriptsafe#279]
**What's changed from v1.0.9.1 to aid in beta testing:**

<ul>
	<li>Added new "Recent Log" page where you can view all recently blocked or allowed items (the "Log" link can be found in the top-right corner of the ScriptSafe panel)</li>
	<li>Added the ability to block Browser Plugin Enumeration (under Fingerprint Protection, option is disabled by default so feel free to enable it)</li>
	<li>Added the ability to block Bluetooth Enumeration (under Fingerprint Protection, option is disabled by default so feel free to enable it)</li>
	<li>Added ability to control whether or not Remove Possible Hash Tracking applies to whitelisted sites or not (default: disabled)</li>
	<li>Added ability to control the Keyboard Fingerprinting Protection keypress delay</li>
	<li>Improved Browser User Agent Spoofing and added ability to enter a custom user agent string</li>
	<li>Added more browser and operating systems for User Agent Spoofing (thanks nyancat18)</li>
	<li>Improved WebGL Fingerprint Protection</li>
	<li>Improved Clipboard Interference Protection</li>
	<li>Fixed "Trust" option not being available for domains starting with a wildcard match</li>
	<li>Improved syncing reliability and added support for handling data compression (to be switched on in an upcoming update)</li>
	<li>Added Polish locale (thanks Galileusz)</li>
	<li>Minor updates to German, Japanese, Chinese (Traditional), and Spanish locales</li>
	<li>Updated unwanted content providers list</li>
	<li>Improve domain matching logic</li>
	<li>Minor panel updates</li>
</ul>

There are two ways you can help test:

**1) Testing v1.0.9.2 functionality, minus syncing**

Instructions:

1. Download the v1.0.9.2 BETA: **https://github.com/andryou/scriptsafe/releases/download/v1.0.9.2_beta/ScriptSafe_v1.0.9.2_BETA.zip**
2. Extract the ZIP file to its own folder anywhere on your computer
3. Copy and paste **chrome://extensions** into your browser address bar and press Enter
4. Make sure you have disabled the Chrome Web Store version of ScriptSafe (ID: oiigbmnaadbkfbmpbfijlflahbdbdgdf)
   - Note: you may want to save a copy of your existing ScriptSafe settings at this point (see https://www.andryou.com/scriptsafe/frequently-asked-questions/#backup)
5. Enable “Developer Mode“
6. Click on **Load unpacked extension**, navigate to the folder you extracted ScriptSafe to in step #2 and click on OK
7. (optional) Import your existing ScriptSafe settings into the beta instance: https://www.andryou.com/scriptsafe/frequently-asked-questions/#restore

**2) Testing v1.0.9.2 functionality + syncing**

Because I made changes to code relating to syncing, I've created two .crx files signed with the same key to allow for sync testing.

**ScriptSafe_1091_test.crx is signed with a different key than the one currently on the Chrome Web Store**

Notes:
* You must either set up two Chrome instances on your computer (i.e. official Google + the Portable Apps version - https://portableapps.com/apps/internet/google_chrome_portable), or have multiple devices with Chrome on them.
* You must also be signed all Chrome instances and have syncing enabled in the browser settings for "Extensions".
* If Chrome disables the .crx versions (usually after restarting Chrome/your computer), you must remove them from all instances and re-add them (https://support.google.com/chrome_webstore/answer/2811969?hl=en)

Instructions:

1. Download the following two .CRX files:
* **https://github.com/andryou/scriptsafe/releases/download/v1.0.9.2_beta/ScriptSafe_1091_test.crx**
* **https://github.com/andryou/scriptsafe/releases/download/v1.0.9.2_beta/ScriptSafe_1092_beta.crx**
2. Copy and paste **chrome://extensions** into your browser address bar and press Enter
3. Make sure you have disabled the Chrome Web Store version of ScriptSafe (ID: oiigbmnaadbkfbmpbfijlflahbdbdgdf)
   - Note: you may want to save a copy of your existing ScriptSafe settings at this point (see https://www.andryou.com/scriptsafe/frequently-asked-questions/#backup)
4. Enable “Developer Mode“
5. Drag and drop **ScriptSafe_1091_test.crx** into the Extensions listing page and click on Add when prompted
6. Repeat steps 2-5 for Chrome instance 1, using **ScriptSafe_1092_beta.crx** in step 5 instead.
7. (optional) Import your existing ScriptSafe settings: https://www.andryou.com/scriptsafe/frequently-asked-questions/#restore
8. Ensure "Enable Syncing" in the ScriptSafe options page is enabled in both instances. And I recommend having "Show Sync Notification" and "Show Import Sync Notification" enabled as well for testing purposes.

Any feedback/issues, please add it as a comment here or reply to my email I sent to all beta testers. **If everything looks good, please share this as well!**

Thank you!

**Comment by gameb0y** [comment]
unbelievable! you are back. We missed you Andry... thank you so much

**Comment by gameb0y** [comment]
if enabled "Prevent Clipboard Interference" can't drag video into timeline (any youtube videos)

**Comment by AdamF001** [comment]
Can Confirm That Youtube Timeline Is undraggable when Clipboard Enabled, but if Allowed it works.

**Comment by zoro200** [comment]
after testing 
***if you use a custom user agent your real user agent can be detected with 
java script using Navigator Object app version
![sans titre5](https://user-images.githubusercontent.com/34140394/33451581-c26b086e-d60f-11e7-984c-e580665c5ac3.jpg)
![sans titre4](https://user-images.githubusercontent.com/34140394/33451635-eae3d352-d60f-11e7-81b5-91903d34e3a3.jpg)
also you may need to add an option to hide selected part like accepted languages and hardware part.

****
![sans titre](https://user-images.githubusercontent.com/34140394/33451854-94fdf412-d610-11e7-9a85-7c4e3d3dc298.jpg)
![sans titre6](https://user-images.githubusercontent.com/34140394/33451855-953358dc-d610-11e7-90fd-6f80f53f1ca4.png)

flash plugin still detected.

**Comment by andryou** [comment]
On the horizon:

![2017-12-01_1-14-14](https://user-images.githubusercontent.com/4351175/33470286-6b6d1d6a-d635-11e7-89b5-2bd8470632f5.png)

**Comment by andryou** [comment]
I've been testing the syncing over the past few days (between v1.0.9.1 and the beta) and it seems to be doing well.

Just wanted to check in with those of you who have tried out the beta version, how is everything with it?

**Comment by AdamF001** [comment]
Everything is looking fine, clipboard interference seems to pick up more page elements than 1.0.9.1 which is nice. Working perfectly.

**Comment by andryou** [comment]
v1.0.9.2 released, thank you all for testing!

I'll look into the user agent spoofing more, as well as the material extensions page and where/if hotkey customzation is supported in it.
