### ISSUE TITLE
Clipboard Interface Blocking Breaks YouTube Seek Bar

### ISSUE THREAD

**Issue by 92847586** [andryou/scriptsafe#289]
First of all, thank you for keeping this project going. For a while I thought you had stopped developing it as the updates stopped coming. If you run out of ideas for new things to add, please at least keep updating the unwanted filters list and adding more options to the spoofing lists and make sure the latest Firefox and Chromium is always available in the spoof list.

So yeah, thanks, this is easily my favorite NoScript-like extension out there due to all the fingerprinting options. I just wish it also had some things that NoScript has like "ABE" and the "XSS" blocking thing.

Anyway, this has just started happening since the last update. I also noticed that "clipboard interface" is coming up on lots of sites that it used to not, such as Reddit's front page.

I think maybe the Clipboard Interface blocker is getting false positives and blocking things potentially essential for the page to function properly now.

On YouTube, it results in the seek bar becoming inoperable. I narrowed it down to the Clipboard Interface blocking causing the issue through trial-and-error.

This occurs on Chromium 62.0.3202.62 (Official Build) (64-bit)

Just figured you'd want to know this as it seems to be a rather big issue.

**Comment by andryou** [comment]
Thank you very much for taking the time to report this.

For YouTube, please add youtube.com to the "Prevent Clipboard Interference" option in the Options page under Fingerprint Protection.

Alternatively in the ScriptSafe panel under Blocked Items, click on "Clipboard Interference" and click on "Allow" for youtube.com.

I hope this helps!
