### ISSUE TITLE
ANNOUNCEMENT: Changes to Updates

### ISSUE THREAD

**Issue by andryou** [andryou/scriptsafe#29]
I just wanted to make an announcement regarding updates:

* **Apology:** I apologize for the frequency of updates over the past week. Major updates were made to key parts of ScriptSafe, bugs were found (some very critical), leading to subsequent fixes being pushed out. This led to the number of updates being pushed out. 
  * A lot has been accomplished in the past week in terms of features and optimizations (such as added regex matching support, hotkey support, WebRTC protection)
  * I thank everyone for your patience and for sticking around. I do hope you notice a significant performance improvement in your browsing experience.
* ~~**Respect Same-Domain Issue (#25):** this is one of the bigger issues that I addressed in an update (v1.0.7.8) I uploaded to the Chrome Web Store at 8:45pm eastern yesterday (Sunday, June 5). Ever since it has been in a "Pending Review" status, meaning someone at Google needs to manually approve it before it is pushed out to users. I've just contacted the Chrome Web Store to inquire about the review status and that it is quite an important update.~~ **v1.0.7.8 was manually approved and published 26 hours later by Google.**
* **Constructive Criticism**: I appreciate constructive criticism (and do take them seriously and try my best to improve ScriptSafe, as you can see from submitted issues here). Denouncing my work is not constructive or meaningful. If you're not happy with ScriptSafe, you're free to uninstall it.

Moving forward, you can expect the following:

* More updates being grouped together, and updates being pushed out when a good amount of fixes has been accumulated (exception: if any are critical fixes)
* Less critical issues experienced
* Less frequent updates

Thanks.

**Comment by chrcoluk** [comment]
I am guessing sods law has struck here, with this urgent update been slower than usual for the webstore to update.

End of the day you do this for free, and I respect that hence there is no justification for people been rude to you, the error happened, but you have already said you will react in future to lower the chances of it again. this is good :)

So thank you for this excellent extension and yes the browser does feel faster to use now.

**Comment by andryou** [comment]
@chrcoluk I appreciate it!

Everyone, as promised I will be pushing updates to the Chrome Web Store much less frequently. This repository will always have the latest data and can be downloaded/synced at any time.

But if you still want to disable the update notifications, here are steps:

1. Restart Chrome (required in order for ScriptSafe to update to the latest version, which at this point in time is **v1.0.7.8**)
  * Previously ScriptSafe would automatically update itself causing any session settings to be lost without any warning
  * In recent updates, the update behaviour was changed so that it would notify users that an update is available and wait for the browser to be restarted
2. Go to the ScriptSafe options page
3. Untick **Show Update Notification**

Note: if you disable this option ScriptSafe will still wait for a complete browser restart before updating itself.

**Comment by andryou** [comment]
From this point on I will be posting beta releases here for testing and feedback before pushing them to the Chrome Web Store.

v1.0.7.11 beta is available for testing: more info here - #40

**Comment by Sebb767** [comment]
Thanks for all the work!

**Comment by klepas** [comment]
Thanks Andrew for ScriptSafe and for the dedication to your users.

**Comment by andryou** [comment]
The update notification was completely removed in v1.0.7.11 and I feel things are stable in v1.0.7.12 (which addressed two important issues and was tested + confirmed by the issue reporters).

Development will continue here, and updates (most likely just enhancements) will be pushed to the Web Store when needed/well-tested.

We've come a long way; I realize there were a lot of releases over the two weeks and just wanted to again thank everyone for sticking around and using ScriptSafe :)
