### ISSUE TITLE
v1.0.9.3 BETA (Chrome) - Ready for Testing

### ISSUE THREAD

**Issue by andryou** [andryou/scriptsafe#296]
**What's changed from v1.0.9.2 to aid in beta testing:**

<ul>
							<li>Added ability to temporarily disable ScriptSafe via the panel</li>
							<li>Added ability to selectively allow Browser Plugins Enumeration (#291)</li>
							<li>Added ability to randomize user agents: on every request or every x minutes (#69)</li>
							<li>Minor panel tweaks</li>
							<li>Minor user agent fix</li>
							<li>Updated unwanted content providers list</li>
						</ul>

**Notes on some of the new features:**
- the temporary disable buttons can be made visible if you click on the "Disable" button in the ScriptSafe panel once: 5m, 15m, 30m, 1h, Forever
- a test page to test the new Browser Plugins Enumeration heading in the panel: http://abc7.com/live/
- and now the fun one: user agent spoofing:
   - under "Privacy Settings", set "User-Agent Spoof" to Custom
   - a textarea will appear where you can enter user agent strings. Enter new ones on new lines.
   - if it detects you've entered multiple user agents, a "Random" dropdown will appear underneath allowing you to set it to: -Off-, Every x Minutes, Every Request
      - Off: only the first user agent string is used
      - Every x Minutes: if selected, a box to set the value appears to the right. Defaults to 5 minutes. ScriptSafe will automatically randomize the user agent every x minutes.
      - Every Request: a random user agent out of the ones in the textarea is selected and used on every request
- the user agents are synced using the new compression method mentioned in https://www.andryou.com/2017/12/04/scriptsafe-whats-coming-to-chrome-syncing/
   - I hope to enable compression for the blacklist, whitelist, and fingerprint lists soon, after giving enough time for everyone to upgrade to at least v1.0.9.2
- I've added chevrons/arrows to the fingerprinting headings in the panel to make it clearer that they have options

**Instructions:**

1. Download the v1.0.9.3 BETA: **https://github.com/andryou/scriptsafe/releases/download/v1.0.9.3_chrome/ScriptSafe_v1.0.9.3_BETA2.zip**
2. Extract the ZIP file to its own folder anywhere on your computer
3. Copy and paste **chrome://extensions** into your browser address bar and press Enter
4. Make sure you have disabled the Chrome Web Store version of ScriptSafe (ID: oiigbmnaadbkfbmpbfijlflahbdbdgdf)
   - Note: you may want to save a copy of your existing ScriptSafe settings at this point (see https://www.andryou.com/scriptsafe/frequently-asked-questions/#backup)
5. Enable “Developer Mode“
6. Click on **Load unpacked extension**, navigate to the folder you extracted ScriptSafe to in step #2 and click on OK
7. (optional) Import your existing ScriptSafe settings into the beta instance: https://www.andryou.com/scriptsafe/frequently-asked-questions/#restore

**If you wish to test user agent list syncing, please download https://github.com/andryou/scriptsafe/releases/download/v1.0.9.3_chrome/ScriptSafe_v1.0.9.3_BETA2.crx and install on Chrome instances where you are signed in + have Extensions syncing enabled**

Any feedback/issues, please add it as a comment here or reply to my email I sent to all beta testers. **If everything looks good, please share this as well!**

Thank you!

**Comment by gameb0y** [comment]
Canvas Fingerprint Protection: (random readout) not working

https://browserleaks.com/canvas
![untitled](https://user-images.githubusercontent.com/19530450/33783744-e261b93c-dc55-11e7-8d61-110d33d15ee5.jpg)

**Comment by andryou** [comment]
@gameb0y: nice catch, I've done some testing and it's related to the Browser Plugins option. Setting configurable from false to true (ss.js, line 152) resolves the issue on https://browserleaks.com/canvas while blocking enumeration (test page: https://panopticlick.eff.org/results?aat=1#fingerprintTable)

**Comment by gameb0y** [comment]
@andryou you are right! if disabled "Block Browser Plugin Enumeration" everything works fine

**Comment by andryou** [comment]
**If you downloaded the beta file, please download it again**

The issue reported by @gameb0y caused issues on a number of sites such as Gmail and Google Docs (if "Block Browser Plugin Enumeration" was enabled). Because of this possibly impeding testing, I've recompiled the beta with the fix.

**Comment by andryou** [comment]
I'm looking to push a Chrome and Firefox release out some time tomorrow, especially to fix #295. I hope people are finding the items in the changelog working well.

If anyone's curious, I submitted a new release to Opera on December 6th for approval; no news yet. I'll wait for that submission to be approved before submitting a new version.
