### ISSUE TITLE
Add support for new tab pages

### ISSUE THREAD

**Issue by andryou** [andryou/scriptsafe#30]
Creating a separate issue for this finding found here: https://github.com/andryou/scriptsafe/issues/25#issuecomment-224442234

ScriptSafe should offer users control over as many pages as possible, which includes the new tab page. Progress is being done to achieve this as shown in this screenshot of a dev build:

![2016-06-07_23-47-04](https://cloud.githubusercontent.com/assets/4351175/15882250/d76f52a6-2d0a-11e6-947e-13720e4c48df.png)

**Comment by Aybee** [comment]
Very good, I'm curious about it.

**Comment by Dinoguy1000** [comment]
Will this also cover [Tab for a Cause](https://chrome.google.com/webstore/detail/tab-for-a-cause/gibkoahgjfhphbmeiphbcnhehbfdlcgo), since that extension replaces the default new tab page? (I'm assuming there are other extensions which similarly do their own thing with/replacing the new tab page, in which case you should interpret this question as including them, but I personally am only aware of/use Tab for a Cause.)

**Comment by andryou** [comment]
@Dinoguy1000 I did a quick test and Tab for a Cause seems to not be filterable by ScriptSafe (as it is a chrome-extension:// url). The native new tab page seems to be an exception since it's a loader for a page hosted on google.[region].

@aybee, feel free to close this issue once you've had a chance to test it out in v1.0.7.9. Thanks!

**Comment by Aybee** [comment]
After a short test everything looks good to me. Thank you very much.

**Comment by Dinoguy1000** [comment]
Are chrome-extension:// URLs inherently unfilterable, or is it more a matter of being more trouble than it's worth or something?

**Comment by andryou** [comment]
They are inherently unfilterable, along with https://chrome.google.com/webstore

**Comment by Dinoguy1000** [comment]
That's a bit of a bummer, since some malware installs or consists of malicious extensions. Am I correct in assuming this means they bypass the blacklist and whitelist?

**Comment by andryou** [comment]
Unfortunately I believe you are correct. This issue consisted of me removing a limit on ScriptSafe that previously limited filtering to only URLs that started with "http", so now it will filter what it has access to. I believe Chrome sandboxes each extension so they are unable to filter each other.

**Comment by Dinoguy1000** [comment]
That's even more of a bummer, though I can definitely understand why it does that, and from an overall security perspective it's better than the alternative. If you haven't already, it would be good to document this particular quirk and note that it means ScriptSafe won't and can't protect against malicious extensions.

**Comment by Dinoguy1000** [comment]
Well, this is interesting. Apparently, Tab for a Cause's new tab works as just a normal new tab, at least some of the time.

![image](https://cloud.githubusercontent.com/assets/818183/15947221/0ef8f47e-2e60-11e6-957a-1516a112116e.png)
