### ISSUE TITLE
Feature request: paired whitelist for thirdparty domains (with wildcard) per referring (main) domain

### ISSUE THREAD

**Issue by LeeteqXV** [andryou/scriptsafe#31]
I do NOT dare/want to trust for example googlevideo.com that is serving up videos to youtube.com, or brightcove.com, cloudflare.com or akamai.net etc., which streams multimedia or serves content for a lot of unknown web sites. Part because of security concern (possibly moot/paranoid, see below), part because I want to avoid multimedia autoplay on (most) sites.

I know that this might be moot in context with choosing to trust the main domain in the first place.
If I choose to enable JS for a new, unknown site, then I am obviously already exposed and at risk, ok. Bear with me for a minute, please:

- What if it is not the main site that has been compromised, but actually brightcove or akamai or googlevideo? And what if it is only that site's user account with those big providers that has been compromised, but not all other user accounts there? I would like to have partial control on where block most, but not all, depending on the main domain.

Moreover, I am not sure as of how exactly this part of Scriptsafe actually works, so let me describe the uncertainty:

a) What exactly happens "behind the scenes" when I have JS turned off by default, visit a new, unknown (untrusted) web site (domain) that streams content from cloudflare.com or amazon-aws ? If I previously have whitelisted cloudflare.com for a different web site which I do trust, will that trust allow this new, unknown web site to automatically serve content from there, even BEFORE that unknown site is allowed to run JS? (Can something go on server-to-server between that domain and cloudflare.com, which is not blocked by my Scriptsafe settings? Hopefully not, but I would like to be sure about that part.)

b) I am not sure, but if a) is moot, is it even remotely possible to have multimedia content streamed from such thirdparty web sites if they are whitelisted, even WITHOUT allowing JS on the main site? I guess not, as it is probably (mostly) the JS on the unknown site that needs to trigger that thirdparty connection, right? (curious as of if that technically speaking is a necessity, or simply the most normal way of setting things up: can some sites chose to use server-to-server trickery that would allow multimedia content to start streaming even without local JS being allowed?)

I am perhaps just paranoid in this case, and b) is possibly just wishful thinking.

The "real" and most practical concern:

c) Regardless of if a) is moot or not: I do not want media to (always) automatically start streaming. I want to be in control of that through some rules that automate some of it. So I want to block the stream through not permitting JS for the main domain I am visiting, but then allow streaming from those main providers once I have allowed JS for the new domain (if I do that at all).

- but I also want to have the flexibility to PREVENT that autoplay also when I temporarily allow JS. So I want a flexible setting for how this pair should be trusted in tandem, so to speak.

Examples:

- I do want to keep JS off and turn them manually on for Youtube. But I do NOT want to go through the *.googlevideo.com variants that keeps changing for each video (and multiple entries per page/video as well...), once I have (temporarily) allowed JS for YT. So what I would prefer in the case of YT is to whitelist *.googlevideo.com automatically, but only in effect after I (temporarily) allow JS for YT and reloads that page. And only for the pair/combination of YT and googlevideos.com. Not automatically permitting any other site that may use googlevideo.com (if any).

- same goes for videos served through brightcove.com: I want to disallow brightcove for all domains in general, but automatically trust it whenever I turn on JS for specific sites that are already in the (new) "paired whitelist" that I am suggesting here.

I want to be able to AVOID trusting those same sites automatically. Hence the whitelist "pairing". Whenever I (permanently) allow/trust JS for example for cloudflare.com to run at a selected domain, cloudflare.com should NOT be allowed to automatically run its JS on any other sites that are NOT in the "paired whitelist". And that whitelist needs to cover wildcards/subdomains (*.brightcove.com, *.cloudflare.com, etc.)

Does this make sense?

And btw;
Another uncertainty of mine, perhaps just an addition to the FAQ etc.:

- Does "Trust" ("trust entire domain") mean that ONLY the JS on that particular domain and its subdomains will be allowed, OR does it mean that ALSO any other thirdparty sites called by that domain will automatically have its JS allowed on that particular domain? (Hope/assume not, but that is unclear to me, perhaps this should be clarified both on the options page, in the FAQ and in the QuickStart guide? - the latter states: "Trust: adds the entire domain to the whitelist (*.abc.com). Content on video.abc.com and js.abc.com will be allowed to load." I would prefer it to be specifically stated that the trust does not extend to thirdparty sites "trusted/used" by that main domain as well. This question also should be addressed in the FAQ, IMO.)

**Comment by Aybee** [comment]
Maybe it will be better to show a short and clear actual-theoretical comparison in graphical, table or list form as it is very hard to filter out the points from such a long running text.

**Comment by andryou** [comment]
> a) What exactly happens "behind the scenes" when I have JS turned off by default, visit a new, unknown (untrusted) web site (domain) that streams content from cloudflare.com or amazon-aws ? If I previously have whitelisted cloudflare.com for a different web site which I do trust, will that trust allow this new, unknown web site to automatically serve content from there, even BEFORE that unknown site is allowed to run JS? (Can something go on server-to-server between that domain and cloudflare.com, which is not blocked by my Scriptsafe settings? Hopefully not, but I would like to be sure about that part.)

With default settings, all resources on it (that you have ticked to disable/block in ScriptSafe's options) are blocked on a new untrusted/unallowed web site, even if you have whitelisted (allowed/trusted) them.

> b) I am not sure, but if a) is moot, is it even remotely possible to have multimedia content streamed from such thirdparty web sites if they are whitelisted, even WITHOUT allowing JS on the main site? I guess not, as it is probably (mostly) the JS on the unknown site that needs to trigger that thirdparty connection, right? (curious as of if that technically speaking is a necessity, or simply the most normal way of setting things up: can some sites chose to use server-to-server trickery that would allow multimedia content to start streaming even without local JS being allowed?)

The JS on the unknown site does need to trigger the third-party connection. Basically the logic in ScriptSafe is: if a domain is not whitelisted and the default mode is set to "Block", it treats unknown domains as a blocked domain, locking it down.

> c) Regardless of if a) is moot or not: I do not want media to (always) automatically start streaming. I want to be in control of that through some rules that automate some of it. So I want to block the stream through not permitting JS for the main domain I am visiting, but then allow streaming from those main providers once I have allowed JS for the new domain (if I do that at all).

As mentioned in A, this degree of security is offered in ScriptSafe. I've rewritten part of the core logic in recent updates to be more strict on unknown domains referencing whitelisted domains.

> I do want to keep JS off and turn them manually on for Youtube. But I do NOT want to go through the *.googlevideo.com variants that keeps changing for each video (and multiple entries per page/video as well...), once I have (temporarily) allowed JS for YT. So what I would prefer in the case of YT is to whitelist *.googlevideo.com automatically, but only in effect after I (temporarily) allow JS for YT and reloads that page. And only for the pair/combination of YT and googlevideos.com. Not automatically permitting any other site that may use googlevideo.com (if any).

You will need to remove the built-in "\*.googlevideo.com" entry and use the "Temp." button for YouTube and the unique x.googlevideo.com URL the video is streaming from

> I want to be able to AVOID trusting those same sites automatically. Hence the whitelist "pairing". Whenever I (permanently) allow/trust JS for example for cloudflare.com to run at a selected domain, cloudflare.com should NOT be allowed to automatically run its JS on any other sites that are NOT in the "paired whitelist". And that whitelist needs to cover wildcards/subdomains (*.brightcove.com, *.cloudflare.com, etc.)

Very interesting idea, but it would be difficult for me to incorporate this and maintain (e.g. pairing specific domains with each other).

> Does "Trust" ("trust entire domain") mean that ONLY the JS on that particular domain and its subdomains will be allowed, OR does it mean that ALSO any other thirdparty sites called by that domain will automatically have its JS allowed on that particular domain? (Hope/assume not, but that is unclear to me, perhaps this should be clarified both on the options page, in the FAQ and in the QuickStart guide? - the latter states: "Trust: adds the entire domain to the whitelist (*.abc.com). Content on video.abc.com and js.abc.com will be allowed to load." I would prefer it to be specifically stated that the trust does not extend to thirdparty sites "trusted/used" by that main domain as well. This question also should be addressed in the FAQ, IMO.)

Yes, "Trust" means that only resources belonging to a domain (and subdomains) are allowed, **not** third-party sites called by any page hosted on the trusted domain. Thanks for the note: I will revise the note.

I appreciate the time you took in posting this issue, and please let me know if you still have any questions/concerns. We share the same "paranoia" afterall; which led me to create ScriptSafe in the first place :)

**Comment by Aybee** [comment]
uMatrix does this pairing thing for example.
https://chrome.google.com/webstore/detail/umatrix/ogfcmafjalglgifnmanfmnieipoejdcf?utm_source=chrome-app-launcher-info-dialog 
Syntax:
https://github.com/gorhill/uMatrix/wiki/Rules-syntax

**Comment by andryou** [comment]
I've created a new option, **Paranoia Mode**:

* If "Respect Same-Domain" is enabled: ScriptSafe will block allowed **third-party** domains (whitelisted or temp.) on an unknown tab.
* If "Respect Same-Domain" is disabled: ScriptSafe will block **all** allowed domains (whitelisted or temp.) on an unknown tab.

![2016-06-08 19_41_23](https://cloud.githubusercontent.com/assets/4351175/15914691/06630fde-2db1-11e6-9ee5-524709e32d25.png)

By default this is off (as this ignores whitelist settings), but you can enable it. (related commit: https://github.com/andryou/scriptsafe/commit/8932c6c10a02489241f7987fe1267b1d5429014d)

![2016-06-08 19_41_49](https://cloud.githubusercontent.com/assets/4351175/15914696/13cf3558-2db1-11e6-9c34-94d04b463d38.png)

I will work on creating a new FAQ page on here in the Wiki section.

**Comment by Aybee** [comment]
>   (Default: disabled; block allowed domains on unknown tabs)

Shouldn't this better be named
> (Default: disabled; block allowed domains on unlisted domains)

What do you think?

**Comment by andryou** [comment]
Agreed, that will be changed in the next update, thanks!

**Comment by andryou** [comment]
I tried to best implement this feature request as elegantly as possible without creating a third list. With the "Paranoia Mode" enabled (implemented in v1.0.7.9), whitelisted domains on an unlisted domain will be blocked.
