### ISSUE TITLE
v 1.0.7.8

### ISSUE THREAD

**Issue by virtualphil** [andryou/scriptsafe#33]
My safescript version 1.0.7.8 no longer separates blocked from allowed and I do not get a temp allow all button. 

I believe it is still blocking, but everything looks the same when it comes to permissions displayed. 1.0.7.7 is also different, but looks more like the older versions.

![screenshot 2](https://cloud.githubusercontent.com/assets/19823010/15902372/2c24709e-2d6d-11e6-8d59-0cac62e9b110.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/19823010/15902371/2c237428-2d6d-11e6-9d81-b96e704127d9.png)

**Comment by andryou** [comment]
Thanks for this, do you see any weird entries in your whitelist? Is your default mode "Block"?

**Comment by virtualphil** [comment]
No to weird entries and yes to block mode.  Here are my options exported 
out.

annoyances|true
annoyancesmode|relaxed
antisocial|false
applet|true
audio|true
blackList|["**.snipsmart.info","**.trkssrv.com","js-agent.newrelic.com","**.googletagmanager.com","b.scorecardresearch.com"]
classicoptions|false
cookies|true
domainsort|true
embed|true
enable|true
frame|true
iframe|true
image|false
lastSync|1465354010677
linktarget|off
mode|block
noscript|false
object|true
preservesamedomain|false
rating|true
referrer|true
referrerspoof|off
refresh|true
script|true
sync|true
syncenable|true
syncfromnotify|true
syncnotify|true
tempregexflag|true
updatemessagenotify|true
updatenotify|true
useragentspoof|off
useragentspoof_os|off
video|true
webbugs|true
webrtc|default_public_interface_only
whiteList|["*.googlevideo.com.com","**.rapid7.com","**.nashvilleclerk.com","**.tncountyclerk.com","**.zscaler.com","**.proofpoint.com","**.watchguard.com","**.weddingwire.com","**.prelert.com","**.trendmicro.com","**.dhl.com","**.twimgs.com","*","**.baodownnashville.com","**.cowanbenefit.com","**.auctiva.com","**.iqt.org","**.nespower.com","**.cybera.com","**.cigna.com","**.vanderbilthealth.com","**.tnkidney.com","**.humana.com","**.uhc.com","**.earlysgifts.com","**.mybigcommerce.com","**.zixmessagecenter.com","**.healthsherpa.com","**.idg.tv","**.opendns.com","**.politico.com","**.corporateboxoffice.com","**.kohls.com","**.vagaro.com","**.nashvillethaimassage.com","**.marriott.com","**.gstatic.com","**.ask.com","**.irfanview.com","routerlogin.net","**.contentdirect.tv","**.llnwd.net","**.thetubes.com","**.flickr.com","**.trustedsource.org","**.borderware.com","newsinlevels.com","da.feedsportal.com","**.ciscowebex.com","**.brighttalk.com","**.hpe.com","**.datafox.com","**.greenzonesys.com","**.intermec.com","**.cummins.com","**.powertohomes.com","**.fbcdn.net","**.appspot.com","**.withgoogle.com","**.lse-socket.com","**.niksun.com","**.forcepoint.com","**.norwall.com","**.localhost","**.crumbdelacrumb.com","**.voltage.com","**.carbonblack.com","**.accumuli.com","**.skyboxsecurity.com","**.aristotleinsight.com","**.ipviking.com","**.d3js.org","**.norse-corp.com","**.norsecorp.com","**.livingsocial.com","**.nrgtn.com","**.techweb.com","**.foodtrucksnash.org","**.computerweekly.com","**.archives.gov","**.nara.gov","**.treasury.gov","**.ironqloud.com","**.exacttarget.com","**.digijaks.com","**.accenture.com","**.toptenreviews.com","**.esecurityplanet.com","**.carmike.com","**.aolcdn.com","**.ssa.gov","**.socialsecurity.gov","**.securitywizardry.com","**.hyatt.com","**.nist.gov","**.certain.com","**.rottentomatoes.com","**.cloudflare.com","**.xcal.tv","**.riverbed.com","**.javaworld.com","**.itworld.com","**.pluralsight.com","**.printfection.com","**.cellebrite.com","**.github.io","**.steaminggoat.com","**.ap.org","**.giac.org","**.dl-rms.com","**.media.net","**.tiqcdn.com","s.ntv.io","**.twimg.com","**.restapitutorial.com","**.rsa.com","**.cloudfront.net","**.lithium.com","**.rackspace.com","**.menlosecurity.com","**.hubspot.com","**.networkcomputing.com","**.redseal.co","**.cloudlock.com","**.bootstrapcdn.com","**.supercuts.com","**.scotusblog.com","**.join.me","**.avalution.com","**.secureworks.com","**.dell.com","**.tympaniinc.com","**.entuity.com","**.firemon.com","**.paxvapor.com","**.ancestry.com","**.solarwinds.com","**.brightcove.com","**.netbraintech.com","**.veriflow.net","**.lyft.com","**.icejerseys.com","**.nhl.com","**.nhlstatic.com","**.caesars.com","**.totalrewards.com","**.i4go.com","**.serverwatch.com","**.kemptechnologies.com","cdn.jsdelivr.net","app-abd.marketo.com","munchkin.marketo.net","table-games-online.com","card-cloud.com","use.typekit.net","**.a10networks.com","**.googleusercontent.com","**.rover.com","**.alooma.io","**.espn.com","**.thesmilingelephant.com","**.wsmv.com","**.worldnow.com","**.mstreetnashville.com","**.varmour.com","**.arkin.net","**.imdb.com","**.answerscloud.com","**.ferguson.com","**.lightcyber.com","**.computershare.com","**.americanexpress.com","**.zqtk.net","**.huffingtonpost.com","**.google.com","**.github.com","**.btci.com","**.marketwatch.com","**.schneier.com","**.rawstory.com"]
xml|true

**Comment by andryou** [comment]
Thank you! In your whitelist, please remove the entry that's just: *

**Comment by virtualphil** [comment]
Andy,

Thank you, that explains it.  But how did that get there? I have never 
manually edited, I have only used the interface.

Phil

**Comment by andryou** [comment]
It is strange; maybe it is related to the one-time update code which converts all trusted entries to the new regex format (e.g. two stars for trust instead of one), but I've had no issues running this code on all of my instances.

In any case, I'm glad we found the cause!
