### ISSUE TITLE
Outlook web gives Error when using ScriptSafe

### ISSUE THREAD

**Issue by Habwuson** [andryou/scriptsafe#344]
As soon as I login to any email account it gives me this:
":-(
Something went wrong
We can't get that information right now. Please try again later."

I found out that disabling completely ScriptSafe makes Outlook web work again, not even adding it to Whitelist works, just disabling it.

**Comment by malcalevak** [comment]
I had this problem too, but I noticed it briefly showed multiple scripts available to enable, before showing none. I managed to pause things with the debugger to get a good look.

Manually allow ow1.res.office365.com and you should be good to go.

**Comment by Habwuson** [comment]
Wow, many thanks for your answer. I've been disabling it every time I use it, so this really helps a lot. Thank you.
