### ISSUE TITLE
Crash on Chromium without API key

### ISSUE THREAD

**Issue by xyrolaith** [andryou/scriptsafe#37]
I use a [Chromium build](http://chromium.woolyss.com/#windows-64-bit) which does not include the Google API key, so Sync and other Google services do not work. ScriptSafe usually asks on the first start if the Sync service should be used but without the API key it just crashes.
Using a build with the API key and disabling the Sync option, then switching back to the build without the API key also does not work.

**Comment by andryou** [comment]
This is excellent (the build, not the inconvenience). I will tackle this tonight and until I have it working I will not sleep.

I will likely upload a test build of ScriptSafe here for you to test and verify, and once everything looks good and tested, it will be incorporated into a future update.

**Comment by andryou** [comment]
@xyrolaith Test build! https://dl.dropboxusercontent.com/u/784305/scriptsafe-20160611-test.zip

**Comment by xyrolaith** [comment]
Thanks for the fast response.

The test build seems to work so far for me.
One thing I noticed though: It seems to catch less scripts than on another computer with standard Chrome installed but I would have to do further checks to confirm this.

**Comment by andryou** [comment]
Very interesting, please let me know. Huffington Post would be a good test site, just make sure you're using the same settings on both computers.

**Comment by andryou** [comment]
@xyrolaith v1.0.7.11 was just officially released which addresses this issue. Please confirm when you can and close this issue if resolved. Thanks!
