### ISSUE TITLE
Chrome freezes when loading a page

### ISSUE THREAD

**Issue by rogor** [andryou/scriptsafe#38]
I've been having this issue for the last two days I think, and I have it only when ScriptSafe is enabled.
When I load a page, Chrome freezes for a few seconds. On some websites it isn't really noticeable, but on others it really is. 

Some examples : 
- youtube freezes for *at least* 3 seconds every time I click a link
- every time I load a reddit page, after the page is loaded it freezes for a few seconds (sometimes up to 10) before I can actually interact with the page

**Comment by andryou** [comment]
Thanks for the report, what ScriptSafe, browser, and operating system versions are you running?

**Comment by rogor** [comment]
Windows 10, Chrome Version 51.0.2704.84 m, ScriptSafe v1.0.7.10

**Comment by rogor** [comment]
Using the timeline in chrome developer tools, it seems that the problem is coming from the blockreferrer function (see screenshot, freeeze of 4.5 seconds after loading reddit)
In case it's relevant, I have 1365 domains in my whitelist (is that too much ? :p)

![scriptsafe_timeline](https://cloud.githubusercontent.com/assets/2693832/15986771/2882793a-3011-11e6-83f9-2f11a6d9c2e1.png)

**Comment by andryou** [comment]
Very helpful, thank you!

For now, untick "**Block Click-Through Referrer**", which should resolve this for you.
I'll work on testing and fixing this for the next release.

**Comment by rogor** [comment]
Works perfectly, thanks!

**Comment by andryou** [comment]
The next release will contain this improvement (I'm using a stress test whitelist of 3,845 domains):

![2016-06-11_15-31-12](https://cloud.githubusercontent.com/assets/4351175/15987084/d4b58f3a-2fe9-11e6-946c-00e25a3dbf3f.png)

**Comment by peterlaws** [comment]
I have over 1,700 in mine, and at the moment, **Block Click-Through Referrer** = off seemed to fix it (re: #15 )... Will monitor it..... Just pray lol

**Comment by andryou** [comment]
@rogor v1.0.7.11 was just officially released which addresses this issue. Please confirm when you can and close this issue if resolved. Thanks!

**Comment by rogor** [comment]
Problem solved :) Thanks!
