### ISSUE TITLE
incompatible with Firefox 64

### ISSUE THREAD

**Issue by trueshanti** [andryou/scriptsafe#385]
it seems FF64.0 changed massivly, causing SS to stop working ..

**Comment by johnwmail** [comment]
It work for me (firefox 64 on debian)

**Comment by dracuking** [comment]
Doesn't work for me either on Desktop (Windows 10) or Android (Oreo). When you click on options, it keeps trying to redirect somewhere repeatedly and doesn't display any options.

**Comment by johnwmail** [comment]
Android Oreo?  how did you install it on Android Oreo?

Can you capture screen to let us see?

**Comment by johnwmail** [comment]
Oh, I see it

https://github.com/andryou/scriptsafe/issues/285

**Comment by trueshanti** [comment]
i removed the addon from FF restarted it readded it .. synced my settings and SS is working again .. closing it .. thank you
