### ISSUE TITLE
update page not obvious enough it's ScriptSafe

### ISSUE THREAD

**Issue by terado** [andryou/scriptsafe#39]
When opening Chrome after a ScriptSafe update has taken place, a page is shown detailing the updates. This is brilliant but unlike the options page where a TITLE shows this is ScriptSafe related, the updated page does not have a TITLE and one must read down to realise what this relates to. It would be useful to have a title banner matching that of the options page.

![updated page image](https://cloud.githubusercontent.com/assets/12643460/15987318/24b8b372-301c-11e6-8250-f15f026c5540.png)

![options page image](https://cloud.githubusercontent.com/assets/12643460/15987333/a36cdaa4-301c-11e6-8207-07cf45f9e7bd.png)

**Comment by andryou** [comment]
@terado this is excellent feedback, thank you. It makes sense and I'll incorporate this in the next update.

**Comment by andryou** [comment]
v1.0.7.11 was officially released which addresses this issue :)
