### ISSUE TITLE
v1.0.7.11 Beta: Help Test!

### ISSUE THREAD

**Issue by andryou** [andryou/scriptsafe#40]
**Changelog for this version:**

<ul>
			<li>Further important compatibility fixes for ScriptSafe to work in Chrome-derivative browsers (e.g. not crash) (issue #36 and #37)</li>
			<li>Greatly reduced page load times/CPU usage if you have large lists and "Block Click-Through Referrer" enabled (#15 and #38)</li>
			<li>Better behaviour when visiting pages on blocked domains</li>
			<li>Removed update notification messages based on feedback</li>
			<li>Better handling of post-page-load inserted content</li>
			<li>Updated unwanted content providers list</li>
		</ul>

As well, the update page now includes the ScriptSafe title (#39)

If you're interested in helping out and testing this version, skip to step 2 in the second set of steps on: https://github.com/andryou/scriptsafe/wiki/Frequently-Asked-Questions#how-do-i-install-the-latest-version (it shouldn't take more than 2 minutes to get set up)

**In addition to the above**, if you'd like you can export your current ScriptSafe settings and lists into the beta version (I recommend doing this):

1. Go to the Options page for your current ScriptSafe version
2. Copy everything in the **Export** box at the bottom of the page into a text editor
3. Set up the beta version (using the link above)
4. Open the beta version's Options page, and copy/paste the contents you saved in step 2 into the **Import** box and click on Import

**Download: https://dl.dropboxusercontent.com/u/784305/scriptsafe1.0.7.11_beta.zip**

If you find any issues, please check if there is an existing issue for it (https://github.com/andryou/scriptsafe/issues) or comment here.

If you don't run into any issues, I'd appreciate it if you could also comment here to let me know!

Thank you!

**Comment by belgacea** [comment]
Works like a charm !

**Comment by andryou** [comment]
Thanks! Just wanted to post a note: I've updated the beta file above with the latest code changes.

**Comment by andryou** [comment]
I'm hoping to push out an update tomorrow seeing how two of the updates in this beta are pretty important: 1) compatibility fixes for Chrome-derivative browsers, and 2) reduced page load times/CPU usage (if you have large lists and "Block Click-Through Referrer" enabled).

I will try to wait for more feedback/confirmation that things are good in this beta version before pushing this out on the Web Store.

As always, thank you all for not only using ScriptSafe, but also contributing your time in testing and providing feedback to make it even better.

**Comment by andryou** [comment]
I've just pushed v1.0.7.11 out onto the Web Store.

I tested it in Chrome, Chromium (Windows and Linux), Iron, a build of Chromium without sync/WebRTC, each with a whitelist of over 3,500 domains over the past 3 days.

The two major issues this release addresses were also individually confirmed in their respective issues here: #36, #37, #15 and #38.
