### ISSUE TITLE
ScriptSafe crashes on Iron without webRTC

### ISSUE THREAD

**Issue by Dwarden** [andryou/scriptsafe#42]
1.0.7.10 is always crashing with Iron browser 51.0.2700 builds compiled w/o WebRTC

**Comment by andryou** [comment]
Can you please help test the beta version that is supposed to fix this issue? https://github.com/andryou/scriptsafe/issues/40

Feel free to comment in that issue if it works for you.

Thanks!

(duplicate of #36 and #37)
