### ISSUE TITLE
Cannot Open Images on Tweetdeck with Block Click-Through Referrer Enabled

### ISSUE THREAD

**Issue by Lanoom** [andryou/scriptsafe#43]
OS: Windows 10; Threshold 2 (Build 10586)
Browser: Chrome ver. 51.0.2704.84 m
Scriptsafe ver. 1.0.7.11
Affected site: https://tweetdeck.twitter.com/

With the Block Click-Through Referrer option enabled, I cannot open up images in my feeds to view them at larger size. They will load at small size within the feeds, my mouse cursor will change to the magnifying glass when hovering over them, but clicking does nothing.

With BCTR disabled, behavior returns to normal upon a page refresh. Turning the setting back on and refreshing causes the issue again.

**Comment by andryou** [comment]
Was able to reproduce. Thanks for the information!

**Comment by andryou** [comment]
This should be resolved in the v1.0.7.12 release I just pushed out. Just make sure "Only on Unwhitelisted Domains" is selected for BCTR.

Please close this issue if it's fixed. Thanks!

**Comment by andryou** [comment]
Marking this as closed!
