### ISSUE TITLE
Last Pass no longer working? After latest update

### ISSUE THREAD

**Issue by NM8Services** [andryou/scriptsafe#45]
Sorry I'm total newb so I know I'm not going to ask the right way but I have been a long time user and have been able to follow your directions for a long time to make things work well enough to stay out of trouble but now my last pass is no longer working unless I disable. This just happened this morning. 1.0.7.11 update. Is there a setting or something I am missing now?

**Comment by andryou** [comment]
Thanks for this, it will be fixed in the next update. I'll spend today testing. Sorry for any inconvenience.

**Comment by andryou** [comment]
This should be resolved in the v1.0.7.12 release I just pushed out. Please close this issue if LastPass is working again with ScriptSafe enabled :)

**Comment by NM8Services** [comment]
That did it. Thank you! You are awesome!

**Comment by andryou** [comment]
@NM8Services no you're awesome, thanks for using ScriptSafe for all this time!
