### ISSUE TITLE
Unable to fully use Tweetdeck 

### ISSUE THREAD

**Issue by Lwrz** [andryou/scriptsafe#46]
With the recent updates to ScriptSafe it halts Tweetdeck features by not allowing the user to open images nor links. Cannot manually find a fix for it either in the options of ScriptSafe.

**Comment by andryou** [comment]
Make sure Block Click-Through Referrer is either disabled or ideally set to
Only on Unwhitelisted Domains. If the latter, make sure
tweetdeck.twitter.com is whitelisted. Let me know if this helps!

**Comment by Lwrz** [comment]
Disabling Block Click-Through Referrer solved the issue although whitelisting Tweetdeck's domain did not. Thanks for the speedy reply and quick fix.

**Comment by andryou** [comment]
Great, thanks for letting me know :)

**Comment by jimbo1qaz** [comment]
"Block Click-Through Referrer" also causes Twitter reply flickering: Red underlines flicker. When I select text using the keyboard (shift-left/right, selected text becomes unselected.

Why does this happen?
