### ISSUE TITLE
Subscription list

### ISSUE THREAD

**Issue by belgacea** [andryou/scriptsafe#48]
I wanted to know if there are existing public filter lists for ScriptSafe, just as Adblock/Plus or Ghostery. Otherwise, is there any plans to build a database to share all our configs ?

**Comment by andryou** [comment]
The latest blocklists from MVPS HOSTS, hpHOSTS (ad / tracking servers), Peter Lowe's HOSTS Project, MalwareDomainList.com) are used in ScriptSafe (if "Unwanted Content Provider" is enabled), but there are no plans for a database with user configs.

The main reason is that user blacklists/whitelists are something I do not want to process or transmit as I know some can be sensitive, and I've received many offers to sell ScriptSafe to third-parties (presumably to inject analytics on browsing behaviour and user blacklists/whitelists), but just to be clear: **I will never sell ScriptSafe**.

I believe ScriptSafe is a personal experience and it is difficult to "prescribe" what domains should be whitelisted or blacklisted as everyone has different security/privacy needs.

I hope this answers your question!

**Comment by belgacea** [comment]
I understand your point. I was just wondering why there wasn't any subscription lists, as I lost my whitelist with the last beta test. Luckily, ScriptSafe has the syncing feature ;)
Thanks for your explanation, it's nice to see there is still people who cares about privacy.
