### ISSUE TITLE
Cannot play TED video if scriptsafe is enabled

### ISSUE THREAD

**Issue by Gunni** [andryou/scriptsafe#49]
See: http://www.ted.com/talks/daniele_quercia_happy_maps

if enabled but not whitelisted, no player

If enabled but whitelisted, nothing on play

If disabled, player and works

**Comment by andryou** [comment]
Please whitelist the below domains:

ted.com
hls.ted.com
pa.tedcdn.com
pb.tedcdn.com

**Comment by Gunni** [comment]
No related domains popped up for me when i was there last, will check again when i get home later today.

**Comment by peterlaws** [comment]
Whitelisting their cdn's worked for me, fyi

**Comment by andryou** [comment]
@Gunni could you let me know if you're still having problems playing TED videos after whitelisting the 4 domains I mentioned? Thanks!

**Comment by Gunni** [comment]
Yea i figured it out.

It worked out and later i just gave up on the plugin... The web has become too reliant on javascript for it to be navigateable without it... :(

**Comment by andryou** [comment]
@Gunni I appreciate the follow-up! All the best to you :) (and your country in Eurocup!)
