### ISSUE TITLE
Wildcards on subdomain in a whitelist don't allow scripts to execute

### ISSUE THREAD

**Issue by fullerth** [andryou/scriptsafe#5]
Adding a wildcard on a subdomain to the whitelist does not allow scripts on the subdomain.

Steps:
1. add `*.client-channel.google.com`
2. visit `mail.google.com` with a logged in account, wait for the hangouts app to load
3. Observe `<num>.client-channel.google.com` in the blocked resources list

These servers are used by the hangouts application and are not accessed for up to 20 seconds after page load (on this machine).

**Comment by andryou** [comment]
Was able to reproduce this. Going to tackle basic regex support in the next release!

**Comment by andryou** [comment]
Update: I've completely rewritten the domain matching logic, doing testing today and if all goes well, you will see a ScriptSafe update tomorrow :)

**Comment by andryou** [comment]
Just pushed the new version, v1.0.7.0, it should auto-update for you within 12 hours! Please let me know if this issue is resolved for you after you receive the update.

**Comment by fullerth** [comment]
Working great now, thanks for the quick update!
