### ISSUE TITLE
update breaks Disqus comments

### ISSUE THREAD

**Issue by holmegm** [andryou/scriptsafe#50]
I'm no stranger to tweaking ScriptSafe settings (and also no expert), but this one seems to be defeating me. 

Disqus comments are used by a HUGE percentage of the web, and since the latest ScriptSafe update, they will not display for me, though they used to display before the update. 

Console shows this:
VM67:3 Uncaught SecurityError: Blocked a frame with origin "http://dilbert.com" from accessing a frame with origin "http://disqus.com". Protocols, domains, and ports must match.

If I click on the error, the code in question appears to be around line 3 of this:
(function (){
		function processFunctions(scope) {
			var triggerblock = scope.document.createElement('div');

Is this part of the new fingerprinting code?  Is it working as designed?

**Comment by andryou** [comment]
Nice catch. I've just pushed v1.0.7.15 which will be a silent update. Feel free to verify that it addresses this issue and close this issue if does.

In v1.0.7.15 I've implemented a check to ensure it is not modifying cross-domain iframes (e.g. dilbert.com => disqus.com).

**Comment by holmegm** [comment]
That fixed it!  Thanks :)

**Comment by andryou** [comment]
@holmegm you are very welcome, my apologies for the inconvenience!
