### ISSUE TITLE
Uncaught ReferenceError: domainCheck is not defined

### ISSUE THREAD

**Issue by johnsca** [andryou/scriptsafe#51]
ScriptSafe v1.0.7.14
Chrome 51.0.2704.103 (64-bit)

```
Uncaught ReferenceError: domainCheck is not defined
	baddies					@	common.js:10
	postLoadCheck			@	ss.js:213
	(anonymous function)	@	ss.js:171
	each					@	jquery.js:2
	each					@	jquery.js:2
	ScriptSafe				@	ss.js:171
```

Worked around by changing Unwanted Content Mode to "strict".

**Comment by andryou** [comment]
Thanks! Just pushed v1.0.7.15 which will be a silent update. Feel free to verify that it addresses this issue (in "relaxed" mode), and close this issue if does.

**Comment by johnsca** [comment]
Excellent, thanks!
