### ISSUE TITLE
[REQ] timezone spoofing / utm remover

### ISSUE THREAD

**Issue by benkhouya** [andryou/scriptsafe#52]
Hi,
First of all thanks for this excellent extension, it's a must have for advanced users of Chrome.

**Requests**
- Can you add an option to block / spoof timezone (very useful when user uses VPN)
- Can you add an option to remove tracking token (utm parameter) from urls?

![timezone difference](http://i.imgur.com/xV8ycIo.jpg)

These options will improve the security and the privacy of ScriptSafe users.
Best regards

**Comment by andryou** [comment]
Beta version now available which addresses both requests :) See: #54

**Comment by benkhouya** [comment]
Great, I'll test it asap.

**Comment by andryou** [comment]
@benkhouya I've just officially pushed out v1.0.8.0, which contains this fix. Feel free to test it out when it arrives on your machine and close this ticket :)

**Comment by benkhouya** [comment]
@andryou Big thanks, it works like a charm.
