### ISSUE TITLE
getClientRects fingerprinting

### ISSUE THREAD

**Issue by gameb0y** [andryou/scriptsafe#55]
The most intersting fingerprinting vector I found on Tor Browser is getClientRects. Is strange that reading back from a canvas has been prevented but simply asking the browser javascript API how a specific DOM elements has been drawn on the screen has not been prevented or protected in any way.

getClientRects allows to get the exact pixel position and size of the box of a given DOM element. Depending on the resolution, font configuration and lots of other factors, the results of getClientRects are different, allowing for a very quick and easy fingerprinting vector, even better than the canvas fingerprinting that is fixed.

http://jcarlosnorte.com/security/2016/03/06/advanced-tor-browser-fingerprinting.html

https://developer.mozilla.org/en-US/docs/Web/API/Element/getClientRects

**Comment by andryou** [comment]
Thanks, will be included in the next release.
