### ISSUE TITLE
Re-open Issue: UI doesn't slide out fully

### ISSUE THREAD

**Issue by aantonop** [andryou/scriptsafe#56]
Sorry to re-open this. It seemed to have been fixed briefly in one of the versions, but is now fully broken again

See Issue #4 

Version .7.15
Chrome 49.0.2623.87 (64-bit)
Mac OS X 10.10.5

Symptoms: Clicking ScriptSafe after loading a blocked site, or partially blocked site, in order to Temp or Allow the blocked components - results in partially open UI, only about one-button height. This happens almost EVERY time in a new tab.

Workaround: Click on icon 4-6 times until it opens fully, varying the time between clicks (maybe the varying time is just placebo, but it seems to help)

Level of problem: Makes very hard to use ScriptSafe. Happens several dozen times a day.

Would appreciate another round of tests. I'm willing to pull, install and test a branch specific to solving this issue from github directly, so you can squash the fix into a single version update.

Many thanks, and sorry for re-opening. ScriptSafe is essential to my daily browsing and I depend on it heavily. Thanks for all the work you do!

PS. Bitcoin Address for donations?

**Comment by andryou** [comment]
No need to apologize! Thank you for reporting this :)

I've created two test builds. You can follow the steps in the beta testing issue for instructions on how to set it up: #54 

Here are the test builds:
https://dl.dropboxusercontent.com/u/784305/ScriptSafe_A.zip
https://dl.dropboxusercontent.com/u/784305/ScriptSafe_B.zip

The only difference between the two is the delay value in the popup.js file on line 52 (A = 0ms delay; B = 1ms delay)

This is Beta 2, so you're probably going to be the first to see the revamped Options page! (let me know your thoughts on it!)

My Bitcoin address is included in the Options page in v1.0.17.15 (but I guess it's not very noticeable); it is: 39VJ5L9Yd6WocG6r88uE7ZZnM5J2M5bW92

Thank you, please let me know how things go!

**Comment by andryou** [comment]
And if those don't address the issue, please try these:

https://dl.dropboxusercontent.com/u/784305/ScriptSafe_C.zip (delay value of 50ms)
https://dl.dropboxusercontent.com/u/784305/ScriptSafe_D.zip (delay value of 100ms)
https://dl.dropboxusercontent.com/u/784305/ScriptSafe_E.zip (delay value of 150ms)

**Comment by andryou** [comment]
And here is another test build which uses a completely different method (after everything has been processed, a function is called to set the html and body elements as the height of the content container): https://dl.dropboxusercontent.com/u/784305/ScriptSafe_Z.zip

**Comment by aantonop** [comment]
Running E solved the problem. Currently running E to do some more long-term testing, but so far have not seen the problem occur. 

All other versions failed while testing on the same 7 tabs. 

Methodology: Same 7 tabs, Restarting Chrome between version changes. If a tab fails to open the UI, click again until it opens. Count all clicks, count failures, count how many of the tabs failed. 

Detailed results of testing:

ScriptSafe_A
2 failed tabs out of 7 tabs tried, 7 failed opens out of 30 clicks

ScriptSafe_B
4 failed tabs out of 7 tabs tried, 21 failed opens out of 30 clicks

ScriptSafe_C
5 failed tabs out of 7 tabs tried. 23 failed opens out of 30 clicks. 

ScriptSafe_D
2 failed tabs out of 7 tabs tried. 7 failed opens out of 30 clicks

ScriptSafe_E
0 failed tabs out of 7 tabs tried. 0 failed opens out of 45 clicks - FIXED

ScriptSafe_Z
3 failed tabs out of 7 tabs tried. 6 failed opens out of 30 cli

**Comment by andryou** [comment]
Wow you're amazing, thank you for all the testing! I'll update the beta code to reflect the value in the E variant. I'll also keep this issue open just in case.

**Comment by andryou** [comment]
(@aantonop if that transaction was from you, thank you so much!)

**Comment by aantonop** [comment]
It was, I work in the bitcoin space. Thank you for all the work you've
done, I've used ScriptSafe daily for 2+ years.

On Tue, Jun 28, 2016 at 3:24 PM, Andrew <notifications@github.com> wrote:

> (@aantonop <https://github.com/aantonop> if that transaction was from
> you, thank you so much!)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/andryou/scriptsafe/issues/56#issuecomment-229202788>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABII25zl4m2o_grQFpzfeie89--AAABfks5qQZ8ugaJpZM4I_cTM>
> .
>



-- 
Andreas M. Antonopoulos
andreas@antonopoulos.com
Tel: +1 347 744 9404

**Comment by andryou** [comment]
I've just officially pushed out v1.0.8.0, which contains the fix in variant E. Feel free to test it out when it arrives on your machine and close this ticket :) Thank you again so much @aantonop!

**Comment by aantonop** [comment]
1.0.8.0 fixes this bug. Confirmed by testing. Thank you!
