### ISSUE TITLE
Extension Error

### ISSUE THREAD

**Issue by 13-gou** [andryou/scriptsafe#58]
https everywhere is not working with scriptsafe

Warning:
This extension failed to redirect a network request to https://connect.facebook.net/en_US/sdk.js#xfbml=1&amp;version=v2.5&amp;
 because another extension (ScriptSafe) redirected it to http://connect.facebook.net/en_US/sdk.js.

**Comment by andryou** [comment]
Unfortunately there's not much I can do: https://developer.chrome.com/extensions/webRequest#conflict_resolution

> Only one extension is allowed to redirect a request or modify a header at a time. If more than one extension attempts to modify the request, **the most recently installed extension wins and all others are ignored**. An extension is not notified if its instruction to modify or redirect has been ignored.

I would recommend you uninstall and reinstall HTTPS Everywhere so it has priority. Another way is to disable the "**Remove Possible Hash Tracking**" setting, but I'd personally recommend having it enabled to thwart tracking.

I will close this issue, but I appreciate you taking the time to report this!
