### ISSUE TITLE
Blacklist-whitelist "swap item" facility (enhancement)

### ISSUE THREAD

**Issue by richardh9935** [andryou/scriptsafe#60]
Dear Andry,

Being a klutz, I'm sure I have rows in the Whitelist that ought to be in the Blacklist.  Maybe even the reverse, too.

Could you please consider the ability to move a specific row from one list to the other?  A bit like the FTP utilities move files up and down.  I'm sure this is not essential.

**Comment by andryou** [comment]
Excellent suggestion. This will be included in the next release!

Each entry will have a "Move to ____" (whitelist/blacklist) option. If clicked, a confirmation message will appear and if confirmed, the entry will be moved to the other list.

**Comment by andryou** [comment]
A screenshot:

![2016-07-01_20-12-52](https://cloud.githubusercontent.com/assets/4351175/16537034/75708d92-3fc8-11e6-8ed7-d64ddc669170.png)

**Comment by andryou** [comment]
@richardh9935 v1.0.8.1 Beta has been released which includes the above feature :) See: #64

**Comment by andryou** [comment]
@richardh9935 I've just pushed v1.0.8.1 on the Web Store which includes an update regarding this issue. Please test and close this issue if this is addressed :)

**Comment by richardh9935** [comment]
Andrew,

Tested and all works.  Thanks.  Please close this issue.


richard.

On Sat, 9 Jul 2016 at 05:40 Andrew <notifications@github.com> wrote:

> @richardh9935 <https://github.com/richardh9935> I've just pushed v1.0.8.1
> on the Web Store which includes an update regarding this issue. Please test
> and close this issue if this is addressed :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/andryou/scriptsafe/issues/60#issuecomment-231453815>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATT850DswksT9e20nWENjkHzbScI751Eks5qTqe3gaJpZM4JDjGT>
> .
>
-- 
richard horobin.
