### ISSUE TITLE
bad site in whitelist but can't delete or add to blacklist

### ISSUE THREAD

**Issue by richardh9935** [andryou/scriptsafe#61]
Dear Andrew,
I have a bad site in my whitelist that I cannot delete nor add to the blacklist.  The X doesn't work.

Bad site is **.2o7.net.  I've blacklisted **.2o7.*, but that has not affected the whitelist entry.

What should I do?

eg can I export the whitelist, clear it; edit the exported list; import it?  (or does Import over-write all entries)

**Comment by andryou** [comment]
Hi, what you can try is exporting all of your settings, using a text editor to manually delete the whitelist entry, copy and paste the updated settings into the Import box and import.

**Comment by richardh9935** [comment]
Andrew,

Thanks for your suggestions.

In the end, I decided I probably had too many items in the whitelist
anyway, so I cleared all of it, and I'll build it up as I use the web
sites.  I'm thinking of it as spring cleaning.

richard.

On Sat, 2 Jul 2016 at 10:08 Andrew <notifications@github.com> wrote:

> Hi, what you can try is exporting all of your settings, using a text
> editor to manually delete the whitelist entry, copy and paste the updated
> settings into the Import box and import.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/andryou/scriptsafe/issues/61#issuecomment-230071303>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATT851RpAzw9yAacPGrR8TtZ4Pmp9X-3ks5qRavegaJpZM4JDjfO>
> .
>
-- 
richard horobin.

**Comment by andryou** [comment]
Thanks for the update! The next ScriptSafe update will contain the ability to move entries between the whitelist/blacklist, so I hope that helps in the future. Will close this issue, but feel free to create another one if you run into anything else.
