### ISSUE TITLE
Google Calendar sidebar blocked

### ISSUE THREAD

**Issue by snowbound** [andryou/scriptsafe#65]
I am using the Google Labs .. Google Calendar gadget (
by Ben K and Garry B) in my Gmail account to display my Google calendar. However with the 1.0.8.0 extension enabled in Win7 Pro in Chrome the calendar never loads nor does the extension show that it is blocking any scripts from loading.

**Comment by andryou** [comment]
@snowbound can you let me know which of the following domains you don't have in your whitelist?

mail.google.com
accounts.google.com
apis.google.com
calendar.google.com
plus.google.com
www-gm-opensocial.googleusercontent.com
ssl.gstatic.com
gstatic.com

**Comment by snowbound** [comment]
Is there no way of sorting the whitelist alphabetically?

**Comment by andryou** [comment]
You can untick "Sort by Domain" under Behaviour Settings

**Comment by snowbound** [comment]
I did not have www-gm-opensocial.googleusercontent.com in the whitelist but even after adding it and reloading the gmail page the calendar still failed to display

**Comment by andryou** [comment]
@snowbound thanks for the info! Could you please let me know what your settings are for the following items on the Options page?

* XML HTTP Request Handling
* Remove Google Analytics (UTM) Tracking
* Remove Possible Hash Tracking

Thanks!

**Comment by snowbound** [comment]
XML HTTP Request Handling is Control Cross-Domain Requests
Remove Google Analytics (UTM) Tracking is unchecked
Remove Possible Hash Tracking is unchecked

I reloaded the gmail page again by logging out of the account and back in again and when I look at the ScriptSafe pulldown for the Gmail page it shows no external scripts (This tab has loaded no external resources) and the only thing Allowed is mail.google.com

**Comment by andryou** [comment]
@snowbound I appreciate your help in debugging this; I apologize for any inconvenience. I seem to have been able to recreate this on my machine and will be looking into it.

**Comment by snowbound** [comment]
Ok at least you are seeing it there and can work on it.

**Comment by andryou** [comment]
@snowbound it seems like whitelisting **clients6.google.com** resolves this issue. I'm going to look into why it's not appearing under Blocked Items.

**Comment by andryou** [comment]
@snowbound figured it out! A fix will be incorporated into the next release. Until then I'll leave this issue open :) Thanks again!

**Comment by peterlaws** [comment]
Not sure if this is related.... I think it's now breaking Gmail. I thought it was me, but when you go to click the Settings (any option actually) under the Cog pop-up, nothing happens

**Comment by andryou** [comment]
@snowbound I've just pushed v1.0.8.1 on the Web Store which includes an update regarding this issue. Please test and close this issue if this issue is addressed :)

**Comment by snowbound** [comment]
My Google calendar Labs plugin is working now.

**Comment by andryou** [comment]
Thanks for the update!
