### ISSUE TITLE
Question ?

### ISSUE THREAD

**Issue by mikhoul** [andryou/scriptsafe#67]
I  find your addon browsing the web to find something similar to `"beforescriptexecute"` in Firefox since Chromium don't support it to modify/stop inline script before they are laoded in page with TamperMonkey/Userscript

Could you tell me if I can block  inline script for some webpage only with your addon **?** 

In fact I'd like to be able to specify which scripts I want to block and on which page.

I'm in the process of moving from Firefox to chrome and before making the move I want to be sure I can adapt my UserScripts to Chromium/Vivaldi before making the move.

Regards :smile:

**Comment by andryou** [comment]
> Could you tell me if I can block inline script for some webpage only with your addon ?

You will probably want to set "Default Mode" to Allow, and Blacklist unwanted webpages. I can confirm inline scripts will be blocked.

You also have full control over which scripts load on a page.

I hope this helps!

**Comment by andryou** [comment]
Going to close this issue, but feel free to create another if you need any help!

**Comment by mikhoul** [comment]
@andryou Thanks a lot for the quick answer it will help me a lot to transition, I'm waiting for Vivaldi to have the Sync before transitioning. 

Regards :smile:
