### ISSUE TITLE
On Update Dropdown Menu Not Complete

### ISSUE THREAD

**Issue by grantyn** [andryou/scriptsafe#7]
On most tabs, the dropdown menu is incomplete even though the website was previously whitelisted only showing "Resources (hover each to see paths)" and the bottom line of links. The ScriptSafe icon could be red or green.

This behavior resolved after restart of Chrome.

**Comment by andryou** [comment]
Does this occur on only whitelisted sites, or all sites? And if only whitelisted sites, is there an example page you don't mind sharing for me to test?

**Comment by grantyn** [comment]
It seemed to be only on whitelisted sites (although I didn't do a 
thorough look at all the sites just the ones I had open in tabs.. 
Unfortunately, after I restarted Chrome the behavior went away, so I 
can't give you any examples.

The scenario went like this:
1) I noticed the ScriptSafe icon was no longer in Chrome App section of 
the toolbar.
2) Notification was found that said ScriptSafe needed new permissions
3) I did whatever the app needed and the icon reappeared on the toolbar, 
but now it was red on sites that had been previously whitelisted
4) Left clicking only brought up this dropdown:


5) Left clicking on sites that were not whitelisted brought up the 
expected dropdown (no screenshot, sorry). I didn't try whitelisting the 
site (oops), to see if it changed the dropdown.
6) Restarted Chrome and the behavior stopped.

Grant
Grant Nakamura Photography, LLC

www.grantnakamura.com
www.facebook.com/GN.Photo.LLC
blog.grantnakamura.com

**Comment by andryou** [comment]
If the issue happens again, please let me know :) We'll give this a week?

**Comment by grantyn** [comment]
OK

**Comment by andryou** [comment]
I figured out the issue: after an auto-update, Chrome clears out the tab data that ScriptSafe has stored for existing tabs, leading to the user having to either close a tab and re-open it, or restart Chrome for ScriptSafe to properly function.

I've included a note in the update page that appears when ScriptSafe is auto-updated and if the user has chosen to see the update notification:

"IMPORTANT - due to the number of changes, <strong>it is recommended you restart Chrome</strong>, otherwise you might run into issues with the tooltip for existing tabs"

**Comment by derjanb** [comment]
@andryou You can register this listener to make Chrome update ScriptSafe only on restarts:
https://developer.chrome.com/extensions/runtime#event-onUpdateAvailable

**Comment by grantyn** [comment]
Got your new update and your warning about restarting Chrome was spot on. I was seeing the exact save behavior. New tabs were fine, but the existing tabs showed the red ScriptSafe icon in the toolbar.

Good work. Let's call this closed. Thanks.

**Comment by andryou** [comment]
That's great to hear, thanks @grantyn!

And thank you @derjanb for the info, I should probably spend a weekend going through the API documentation! I will look into incorporating that in the next update.
