### ISSUE TITLE
Unable to read books on Play Store

### ISSUE THREAD

**Issue by 486DX50** [andryou/scriptsafe#72]
I'm unable to read books on Google Play Store using built-iin reader unless I completely disable ScriptSafe. Besides that it's a must have extension. Thank you!!!

**Comment by andryou** [comment]
Have you tried disabling all fingerprint protection settings (and also the remove hash tracking option)?

If so and this still occurs, I have a feeling this is related to #65, which will be fixed in the next release. I'll comment again when I've pushed out the next release for you to test!

**Comment by andryou** [comment]
@486DX50 v1.0.8.4 has been released, can you review the Blocked Items when trying to read books (temporarily allowing them), and see if it allows you to read them?

**Comment by 486DX50** [comment]
I just had to go back and also trust googleusercontent.com additionaly. Problem fixed.
