### ISSUE TITLE
Gmail issue?

### ISSUE THREAD

**Issue by peterlaws** [andryou/scriptsafe#73]
I already mentioned this in #65 ..... I think it's now breaking Gmail. I thought it was me, but when you go to click on any items under the Cog pop-up, nothing happens.

![fireshot 294](https://cloud.githubusercontent.com/assets/9319293/16635391/121cc96c-43ca-11e6-8467-42f50e192dea.png)

**Comment by andryou** [comment]
Do you have "Prevent Clipboard Interference" enabled? That may be the cause.

If not, please try the v1.0.8.1 beta which would probably fix this if this is related to #65 :)

**Comment by peterlaws** [comment]
ok, that was it....
