### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by exrazr** [andryou/scriptsafe#75]
sysinfo:
german user; german windows 7, german chrome 51.0.2704.103 m (64-bit);

scriptsafe WAS great, everything worked fine as it was. last update, it changed the language dependent on the system-settings.
the translation is so bad, i can't even identify which settings they could mean. IF there is a menu to change the language, i can't find it because of it.

solutions: 
1. proper translations (tbh. i don't want/need them) 
2. revert to all english.

ps. ASK the users before changeing their settings !!

**Comment by andryou** [comment]
My sincere apologies, I've just pushed v1.0.8.3 which reverts back to all English and I've added links to the Update and Options pages to https://www.andryou.com/scriptsafe/translate/ which I will use as a status/informative page for translations and translators.
