### ISSUE TITLE
Translation (german)

### ISSUE THREAD

**Issue by Syphdias** [andryou/scriptsafe#76]
Hey,  
just noticed everything switched to german and no way to switch back.
Secondly, the german word "sparen" means "to save money" not "to save setting", use "Speichern" or "Sichern" instead  
Syphdias

**Comment by andryou** [comment]
Hi! Which version do you have installed? The latest should be v1.0.8.4, where I've reverted back to English.

**Comment by Syphdias** [comment]
It was v1.0.8.2, just restarted Chrome to get the new version. Thx
I can try to translate it better if you want (native speaker), but most likely I will continue to use the english version (if possible)

**Comment by andryou** [comment]
Good to hear! Thank you for your offer: someone is already working on translating it :) You can check this page: https://www.andryou.com/scriptsafe/translate/

I'm keeping it updated with who has been emailing me to offer to translate, so that there isn't any duplicated effort.
