### ISSUE TITLE
Twitter page is not working correct

### ISSUE THREAD

**Issue by gameb0y** [andryou/scriptsafe#78]
![untitled](https://cloud.githubusercontent.com/assets/19530450/16712066/eab05e76-463e-11e6-8e11-80b783c2ec88.jpg)

**Comment by stelariusinfinitek** [comment]
No problems here. Make sure you allowed the required domains. If you still have issues, it's something in your settings.


![2016-07-10-095741_1366x768_scrot](https://cloud.githubusercontent.com/assets/18717816/16712118/d5f996b4-4684-11e6-94db-451a20ca81a6.png)

**Comment by gameb0y** [comment]
please enable 'Block Client Rectangles' and try again

**Comment by stelariusinfinitek** [comment]
Yes, after that it went crazy. Leave it unchecked until it's fixed.

**Comment by monotek** [comment]
Adding a **.twimg.com rule to the whitelist manually did the trick for me.
Whats weird is, that twimg.com was not shown in blocked item list.

**Comment by andryou** [comment]
Hi @monotek, just wanted to let you know that v1.0.8.5 will resolve this issue and will be released either later today or tomorrow.

It addresses the issue where some blocked items aren't being listed in the panel, and it also adds the ability to selectively allow Fingerprint Protection options on a per-site basis (e.g. allowing Client Rectangles on twitter.com).

**Comment by andryou** [comment]
v1.0.8.5 which contains a fix for this has officially been released.
