### ISSUE TITLE
Fingerprint Protection - 2 Issues Noticed

### ISSUE THREAD

**Issue by Abdorabih** [andryou/scriptsafe#79]
Hi Andy, 
ScriptSafe is a fabulous extension thank you for such great piece of work.  Just wanted to mention the following two issues i noticed so far.
Youtube does not play videos when Block Battery Fingerprinting is ON.
WhatsappWeb QRC code does not display when Canvas Fingerprint Protection is ON

You are probably aware but i'm interested to know if there will be a fix going forward.

Cheers

NB. I will report further issues as they arise (hopefully not many)

**Comment by stelariusinfinitek** [comment]
I have Block Battery Fingerprint turned ON and I can see videos on youtube.

**Comment by Abdorabih** [comment]
Interesting .. I can watch embedded YouTube videos through other websites but not directly from Youtube.com see screenshot below


![scriptsafe](https://cloud.githubusercontent.com/assets/20381977/16714108/6349e862-46b1-11e6-9ef4-b66e1b65d5db.png)

**Comment by stelariusinfinitek** [comment]
Can you hover your cursor over Battery Fingerprint there so I can see what scripts are blocked?

**Comment by Abdorabih** [comment]
It must be.. because when I switch off battery fingerprint protection , I am able to watch YouTube  videos again. ..

**Comment by stelariusinfinitek** [comment]
Really strange. Are you using Chrome or Chromium?

**Comment by Abdorabih** [comment]
Chrome!

**Comment by andryou** [comment]
v1.0.8.5 which contains a fix for this has officially been released (granular control over fingerprint protection).

@Abdorabih thank you for your kind words and I apologize for the delay in getting to this issue!

**Comment by chipironcin** [comment]
I'd prefer Youtube to allow video playback even if they can retrieve my battery status, not just allow that intrusion. I cannot find any information in the internet about why Youtube may require that information to play a video. Any of you know why? Is something we should put pressure on to not be a requirement?
