### ISSUE TITLE
No "quick search" from address bar

### ISSUE THREAD

**Issue by SvenKortekaas** [andryou/scriptsafe#8]
Plugin: ScriptSafe v1.0.6.19
OS: Windows 10
Browser: Google Chrome Version 51.0.2704.63 m (64-bit)

After installing the plugin I can not use google search from the address bar. I normally type my search request in the address bar but that doesn't work anymore. When entering a search request and hitting 'Enter' it goes to google.com without any search results.

Example:
Type "test search" in my address bar.
Hitting 'Enter'
Result: https://encrypted.google.com/#safe=off&q=test%20search
Without any search results. Just the Google box where I can enter my search request

**Comment by andryou** [comment]
Thanks for submitting the detailed issue! Do you have encrypted.google.com whitelisted?

**Comment by SvenKortekaas** [comment]
That fixed the problem.

**Comment by andryou** [comment]
Thanks letting me know!
