### ISSUE TITLE
Interaction with Ublock Origin

### ISSUE THREAD

**Issue by snowbound** [andryou/scriptsafe#80]
Win 7 Pro UBlock Origin 1.7.6 and ScriptSafe 1.0..8.4

Noticing orange coloured hamburger/chrome menu icon and clicking on it indicates an Extension issue. Scrolling down to UBLock Origin I see errors like the following:

This extension failed to redirect a network request to data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw== because another extension (ScriptSafe) redirected it to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACklEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg==.

**Comment by Enigma0** [comment]
Also seeing this. Could it be made to work a little nicer or perhaps have a setting that sets one extension as a priority in conflicts?

**Comment by snowbound** [comment]
No further progress on this? Still getting almost daily 

This extension failed to redirect a network request to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACklEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg== because another extension (uBlock Origin) redirected it to data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==.

**Comment by Enigma0** [comment]
Yeah without fail every time I launch Chrome I see either ScriptSafe or uBlock Origin throwing these exceptions playing tug-of-war with eachother.

**Comment by snowbound** [comment]
Going to try another script blocker. This issue as well as having to disable this extension for some sites, even though it shows no blocked scripts, to get the site to display properly.

**Comment by andryou** [comment]
Unfortunately this is unavoidable, is beyond what I can do with the extensions API, and is common with Chrome extensions, such as uBlock Origin and Disconnect: https://github.com/gorhill/uBlock/issues/1170#issuecomment-168989068

> In summary, the network requests to Google Analytics are blocked, but only one of the extension will be able to redirect to its neutered script as replacement (I am assuming Ghostery's replacement script is also a neutered version, I did not look into it)
