### ISSUE TITLE
(Chrome) Youtube Videos no load (disable BBF fixes it)

### ISSUE THREAD

**Issue by montiblanc** [andryou/scriptsafe#82]
I tried allowing everything, no luck. other plugins include uBlock Origin & uBlock Origin WebSocket (i tried disabling them too). It seems to be a problem with scriptsafe only, videos load again when i disable it.

Edit: disabling Block Battery Fingerprinting fixed the issue.

**Comment by TjWallas** [comment]
Hi, 

I recently noticed this issue as well and I was wondering if there is a way to disable battery fingerprinting for whitelisted/trusted sites. Perhaps, granular control to enable/disable battery fingerprinting on a per-site basis.

cc @andryou Any suggestions?

**Comment by TjWallas** [comment]
@andryou Maybe, a less rigorous approach for blocking battery fingerprinting would do the trick.

I personally used the script below using Tampermonkey and it did the trick. YouTube video loaded normally afterwards.

```javascript
(function(navi){
   var nnav = new Proxy(navi,{
      get:function(t,p){
         if(p == "getBattery" || p == "battery"){
             return void(0);
         }
         if(t[p] instanceof Function){
             return t[p].bind(navi);
         }
         return t[p];
      },
      has:function(t,p){
         if(p == "getBattery" || p == "battery"){
            return false;
         }
         return p in navi;
      }
   });

   Object.defineProperty(window,"navigator",{
      configurable: false,
      enumberable: false,
      value:nnav,
      writable:false,
   });
})(window.navigator);
```
