### ISSUE TITLE
FR: reload button

### ISSUE THREAD

**Issue by goboating** [andryou/scriptsafe#85]
Great extension, thanks!

It's pretty much 50/50 weather I want to reload or not after a configuration change. Therefore a reload button on the drop-down interface would be most useful.

**Comment by andryou** [comment]
I've released a beta version of v1.0.8.5 which incorporates a fix for this issue: #140. Feel free to test and confirm.

**Comment by andryou** [comment]
v1.0.8.5 which contains a reload button in the panel has officially been released.
