### ISSUE TITLE
No license!

### ISSUE THREAD

**Issue by RyDroid** [andryou/scriptsafe#90]
Hi.

This project seems to have no license! So by default, it is sadly proprietary software.
The license should be clarified. If you want a free/libre one, I advice you to take a look to the list of the FSF: https://www.gnu.org/licenses/license-list.html

Regards.

**Comment by andryou** [comment]
Thank you; will be licensed under GNU GPL: https://github.com/andryou/scriptsafe/commit/2727b097f2ec4f6eef5eb05836207ab4e7cb899d

**Comment by RyDroid** [comment]
Ok, great.
