### ISSUE TITLE
I want to know when will v1.0.8.5 released because I need Chinese Translation very much

### ISSUE THREAD

**Issue by 13597981251** [andryou/scriptsafe#92]

**Comment by andryou** [comment]
Sorry for the late reply: the next release will be made after a couple of major issues are closed, like #127 

Thank you for your patience!

**Comment by andryou** [comment]
I've released a beta version of v1.0.8.5 which incorporates a fix for this issue: #140. Feel free to test and confirm.

**Comment by andryou** [comment]
v1.0.8.5 has officially been released :)
