### ISSUE TITLE
firefox support?

### ISSUE THREAD

**Issue by ibrokemypie** [andryou/scriptsafe#95]

**Comment by MattMS** [comment]
There is [NoScript](https://addons.mozilla.org/en-US/firefox/addon/noscript/) for Firefox, which is similar.

**Comment by andryou** [comment]
Along with what @MattMS mentioned, NoScript is an excellent, feature-rich extension. I currently don't have any plans to develop a Firefox build of ScriptSafe.

**Comment by andryou** [comment]
An update: https://addons.mozilla.org/en-US/firefox/addon/script-safe/
