### ISSUE TITLE
Blacklist Only Mode?

### ISSUE THREAD

**Issue by random6969** [andryou/scriptsafe#96]
I've noticed that your extension breaks many websites (such as Facebook).

While I could manually whitelist each website and/or troubleshoot to determine which parts are causing the issue, I feel it would be much easier if I could instead specify which websites in particular I want your extension to run on (particularly the ones with pop-ups / pop-unders).

I notice your extension already has a whitelist / blacklist section. I'm wondering if there's a way to only use the blacklist (listing the bad websites I want your extension to block, while leaving all other websites alone). Is this possible?

**Comment by andryou** [comment]
Under General Settings, change Default Mode to Allow :)
