### ISSUE TITLE
Add a remark to "Canvas Fingerprint Protection"

### ISSUE THREAD

**Issue by tjuerges** [andryou/scriptsafe#99]
This is not an issue as in bug but it is about adding a remark to the explanation of the "Canvas Fingerprint Protection" setting.

When "Canvas Fingerprint Protection" is set to anything else but "Disabled", What's App Web will not show a QR code for signing in.  A remark about this in the explanation of the setting would be appreciated.

**Comment by andryou** [comment]
v1.0.8.5 has officially been released which now gives you the ability to allow certain Fingerprint Protection options on a per-domain basis :)

**Comment by tjuerges** [comment]
Sorry for not getting back to you earlier.  This works now as expected.  Thank you very much!
